// ============================================================
//  data.js — Base de datos de plantillas n8n
//  Para ampliar: agrega objetos al array TEMPLATES.
//  Campos: cat, name, file (sin extension), desc, flow[[label,tipo]],
//          creds[], uses[], obs[], tags[]
//  Tipos de nodo (color): trigger, ai, action, logic, data, comms, wait
// ============================================================
const CATS = {
  "01-IA-AI":             {name:"IA / AI",             color:"#b06bff"},
  "02-Webhooks-API":      {name:"Webhooks / API",      color:"#00d4ff"},
  "03-Email-Comunicacion":{name:"Email / Comunicación",color:"#ff4a9d"},
  "04-Datos-Scraping":    {name:"Datos / Scraping",    color:"#4a90ff"},
  "05-Productividad":     {name:"Productividad",       color:"#00ff66"},
  "06-Redes-Sociales":    {name:"Redes Sociales",      color:"#ffb000"},
  "07-DevOps":            {name:"DevOps",              color:"#ff5555"},
  "08-Marketing":         {name:"Marketing",           color:"#00e0c0"},
  "09-Industrial-Plantas":{name:"Industrial / Plantas",color:"#ea580c"},
};
const NODE_COLORS = {trigger:"#ffb000",ai:"#b06bff",action:"#00ff66",logic:"#00d4ff",data:"#4a90ff",comms:"#ff4a9d",wait:"#888888"};

const TEMPLATES = [
  // ---------- 01 · IA / AI ----------
  {cat:"01-IA-AI",name:"IA · Resumen de Textos (API)",file:"IA-Resumen-Textos-API",
   desc:"Endpoint HTTP que recibe un texto y devuelve un resumen en 3 puntos clave generado por OpenAI.",
   flow:[["Webhook","trigger"],["OpenAI","ai"],["Responder","action"]],creds:["openAiApi"],
   uses:["Resumir artículos y noticias","Tickets de soporte largos","Hilos de correo","Minutas de reuniones"],
   obs:["Usa gpt-4o-mini para abaratar; cambia a gpt-4o para más calidad","Webhook público: añade Header Auth en producción","responseMode responseNode obligatorio para devolver JSON"],
   tags:["ia","openai","resumen","api","webhook"]},
  {cat:"01-IA-AI",name:"IA · Clasificador de Emails",file:"IA-Clasificador-Emails",
   desc:"Lee correos nuevos de Gmail, la IA los clasifica (urgente/normal/spam/newsletter) y alerta por Telegram si son urgentes.",
   flow:[["Gmail Trigger","trigger"],["Clasificar IA","ai"],["Preparar","data"],["Es Urgente?","logic"],["Telegram","comms"]],creds:["gmailOAuth2","openAiApi","telegramApi"],
   uses:["Triaje automático de bandeja","Priorización de soporte","Filtrado de spam"],
   obs:["Reemplaza TU_CHAT_ID en el nodo Telegram","Trigger de Gmail usa polling cada minuto","El prompt fuerza una palabra → fácil de filtrar en el IF"],
   tags:["ia","gmail","email","clasificar","telegram"]},
  {cat:"01-IA-AI",name:"IA · Generador de Contenido",file:"IA-Generador-Contenido-Redes",
   desc:"Cada día genera un post para redes sociales sobre un tema definido y lo envía a Telegram para revisión.",
   flow:[["Cada Día","trigger"],["Tema","data"],["Generar IA","ai"],["Telegram","comms"]],creds:["openAiApi","telegramApi"],
   uses:["Calendario editorial automático","Borradores diarios","Ideas para community managers"],
   obs:["Programa la hora exacta en el nodo Schedule","Ideal como borrador humano-en-el-loop","Encadena con Buffer/LinkedIn para publicar directo"],
   tags:["ia","contenido","redes","schedule","openai"]},
  {cat:"01-IA-AI",name:"IA · Análisis de Sentimiento",file:"IA-Analisis-Sentimiento",
   desc:"Endpoint que analiza el sentimiento de un texto y devuelve JSON estructurado {sentimiento, score, razon}.",
   flow:[["Webhook","trigger"],["Analizar IA","ai"],["Responder","action"]],creds:["openAiApi"],
   uses:["Monitoreo de marca","Análisis de reseñas","Scoring de leads por tono","Moderación"],
   obs:["response_format json_object garantiza salida parseable","Combina con 04-Datos-Scraping para reseñas web","Listado en n8n FAQ oficial como caso de uso AI"],
   tags:["ia","sentimiento","api","json","openai"]},
  {cat:"01-IA-AI",name:"IA · Transcripción de Audio (Whisper)",file:"IA-Transcripcion-Audio-Whisper",
   desc:"Recibe la URL de un audio, lo descarga y lo transcribe a texto con OpenAI Whisper en español.",
   flow:[["Webhook","trigger"],["Descargar","data"],["Whisper","ai"],["Responder","action"]],creds:["openAiApi"],
   uses:["Notas de voz","Podcasts","Audios de WhatsApp","Minutas de reuniones"],
   obs:["El primer HTTP Request debe devolver binario (file)","Límite de Whisper API: 25 MB por archivo","language:es fuerza español; quítalo para auto-detección"],
   tags:["ia","whisper","audio","transcripcion","openai"]},
  {cat:"01-IA-AI",name:"IA · Chatbot RAG",file:"IA-Chatbot-RAG",
   desc:"Bot de Telegram con Retrieval-Augmented Generation: embedda la pregunta, busca contexto en Postgres vectorial y responde con un LLM local (Ollama).",
   flow:[["Telegram","trigger"],["Embedding","ai"],["Buscar","data"],["LLM","ai"],["Responder","comms"]],creds:["telegramApi","postgres"],
   uses:["Soporte con base de conocimiento","FAQ inteligente","Asistente de documentación"],
   obs:["Usa Ollama local (localhost:11434) — sin coste por token","Requiere tabla docs con columna embedding (pgvector)","Cambia llama3/nomic-embed-text por tus modelos descargados"],
   tags:["ia","rag","chatbot","ollama","telegram","pgvector"]},
  {cat:"01-IA-AI",name:"IA · Traducción Multi-idioma",file:"IA-Traduccion-Multiidioma",
   desc:"Endpoint que traduce un texto al idioma indicado usando OpenAI y devuelve solo la traducción.",
   flow:[["Webhook","trigger"],["Traducir IA","ai"],["Responder","action"]],creds:["openAiApi"],
   uses:["Localización de contenido","Atención multilingüe","Traducción de documentos"],
   obs:["Pasa {texto, idioma} en el body","El prompt fuerza devolver SOLO la traducción","Para idiomas de bajo recurso, gpt-4o rinde mejor que mini"],
   tags:["ia","traduccion","api","openai"]},
  {cat:"01-IA-AI",name:"IA · Generación de Imágenes (DALL-E)",file:"IA-Generacion-Imagenes-DALLE",
   desc:"Endpoint que genera una imagen con DALL-E 3 a partir de un prompt y devuelve la URL.",
   flow:[["Webhook","trigger"],["DALL-E","ai"],["Responder","action"]],creds:["openAiApi"],
   uses:["Imágenes para redes","Miniaturas","Mockups visuales","Arte conceptual"],
   obs:["dall-e-3, tamaño 1024x1024 por defecto","La URL es temporal: descarga la imagen si la necesitas permanente","Combina con 06-Redes-Sociales para publicar directo"],
   tags:["ia","dalle","imagen","openai","api"]},
  {cat:"01-IA-AI",name:"IA · Extracción de Datos de PDF",file:"IA-Extraccion-Datos-PDF",
   desc:"Descarga un PDF, extrae el texto y usa IA para devolver datos estructurados en JSON.",
   flow:[["Webhook","trigger"],["Descargar","data"],["Extraer","data"],["IA","ai"]],creds:["openAiApi"],
   uses:["Facturas y recibos","Contratos","CVs y perfiles","Formularios escaneados"],
   obs:["Descarga debe devolver binario para ExtractFromFile","PDFs escaneados (imagen) requieren OCR previo","Ajusta el prompt system al esquema que necesites"],
   tags:["ia","pdf","extraccion","openai","documentos"]},

  // ---------- 02 · Webhooks / API ----------
  {cat:"02-Webhooks-API",name:"API · Endpoint REST Genérico",file:"API-REST-Generica",
   desc:"Convierte n8n en un microservicio REST: recibe un POST, valida/procesa con JavaScript y responde con código de estado dinámico.",
   flow:[["Webhook","trigger"],["Procesar","logic"],["Responder","action"]],creds:[],
   uses:["Prototipar backends","Glue-APIs entre sistemas","Mocks y endpoints rápidos"],
   obs:["El nodo Code devuelve status usado como HTTP code (400 si falta nombre)","Use case oficial n8n: Backend prototyping","Añade rate-limiting externo y auth en producción"],
   tags:["api","rest","webhook","code","backend"]},
  {cat:"02-Webhooks-API",name:"Webhook · Formulario a Google Sheets",file:"Formulario-a-GoogleSheets",
   desc:"Captura envíos de cualquier formulario web (HTML, Typeform, Tally) y los registra como filas en Google Sheets.",
   flow:[["Webhook Form","trigger"],["Mapear","data"],["Sheets","data"]],creds:["googleSheetsOAuth2"],
   uses:["Captura de leads","Registros de eventos","Encuestas","CRM ligero en Sheets"],
   obs:["Reemplaza TU_SPREADSHEET_ID y verifica la hoja","autoMapInputData crea columnas automáticamente","Entrada típica de los flujos de 08-Marketing"],
   tags:["webhook","sheets","formulario","leads","datos"]},
  {cat:"02-Webhooks-API",name:"Webhook · Stripe Pagos a Slack",file:"Stripe-Pagos-a-Slack",
   desc:"Escucha webhooks de Stripe y notifica en Slack cada venta completada con importe y cliente.",
   flow:[["Webhook Stripe","trigger"],["Pago OK?","logic"],["Slack","comms"]],creds:["slackApi"],
   uses:["Alertas de ventas en tiempo real","Dashboards de equipo","Disparador de fulfilment"],
   obs:["El IF filtra solo checkout.session.completed","amount_total viene en céntimos → se divide /100","Valida la firma Stripe-Signature en producción"],
   tags:["webhook","stripe","pagos","slack","ventas"]},
  {cat:"02-Webhooks-API",name:"API · Paginación de Datos HTTP",file:"API-Paginacion-HTTP",
   desc:"Consume una API paginada recorriendo todas las páginas automáticamente y acumula los resultados en Sheets.",
   flow:[["Cada Hora","trigger"],["Paginar API","data"],["Sheets","data"]],creds:["googleSheetsOAuth2"],
   uses:["Sincronizar catálogos","Volcar listados grandes","Backups de APIs"],
   obs:["La paginación integrada de n8n recorre páginas sola","paginationCompleteWhen: responseIsEmpty detiene al acabar","Adapta el parámetro de página según la API (page/offset/cursor)"],
   tags:["api","paginacion","http","sheets","datos"]},
  {cat:"02-Webhooks-API",name:"Webhook · Typeform a CRM",file:"Typeform-a-CRM",
   desc:"Recibe respuestas de Typeform, las aplana con JavaScript y crea un contacto en HubSpot.",
   flow:[["Webhook","trigger"],["Aplanar","logic"],["HubSpot CRM","action"]],creds:["hubspotApi"],
   uses:["Captura de formularios a CRM","Calificación de leads","Onboarding de contactos"],
   obs:["El Code aplana el array answers de Typeform por ref","Configura el webhook en el panel de Typeform","Mapea más campos añadiendo propiedades en HubSpot"],
   tags:["webhook","typeform","crm","hubspot","leads"]},

  // ---------- 03 · Email / Comunicación ----------
  {cat:"03-Email-Comunicacion",name:"Email · Auto-Responder Gmail con IA",file:"Email-Auto-Responder-Gmail",
   desc:"Detecta correos sin leer, redacta una respuesta profesional con IA y la envía automáticamente.",
   flow:[["Gmail Trigger","trigger"],["Redactar IA","ai"],["Responder","comms"]],creds:["gmailOAuth2","openAiApi"],
   uses:["Atención al cliente 24/7","Respuestas a consultas frecuentes","Primer contacto comercial"],
   obs:["Filtra por unread para no responder dos veces","Pon un filtro de asunto/remitente para evitar auto-respuestas en cadena","Revisa la calidad de la IA antes de activar sin supervisión"],
   tags:["email","gmail","ia","auto-respuesta","openai"]},
  {cat:"03-Email-Comunicacion",name:"Email · Parser de Facturas a Notion",file:"Email-Parser-Facturas-Notion",
   desc:"Filtra correos que contienen 'factura', extrae los datos y los guarda como páginas en una base de Notion.",
   flow:[["Gmail Trigger","trigger"],["Es Factura?","logic"],["Extraer","data"],["Notion","data"]],creds:["gmailOAuth2","notionApi"],
   uses:["Registro contable automático","Organización de facturas","Archivo de comprobantes"],
   obs:["Reemplaza TU_DATABASE_ID de Notion","El filtro por asunto es simple; usa IA para extraer importe/fecha reales","Combina con 04-Datos para adjuntar el PDF"],
   tags:["email","gmail","facturas","notion","parser"]},
  {cat:"03-Email-Comunicacion",name:"Email · Newsletter desde Sheets",file:"Email-Newsletter-Sheets",
   desc:"Cada lunes lee una lista de suscriptores en Sheets y envía un newsletter HTML personalizado a cada uno.",
   flow:[["Cada Lunes","trigger"],["Leer Lista","data"],["Enviar Email","comms"]],creds:["smtp"],
   uses:["Newsletters semanales","Comunicados a clientes","Campañas simples"],
   obs:["Usa credencial SMTP (o Gmail) para el envío","Personaliza con {{ $json.nombre }} por fila","Para listas grandes considera Mailchimp (ver 08-Marketing)"],
   tags:["email","newsletter","sheets","smtp","marketing"]},
  {cat:"03-Email-Comunicacion",name:"Comunicación · Alertas por WhatsApp (Twilio)",file:"WhatsApp-Alertas-Twilio",
   desc:"Recibe una alerta por webhook y la reenvía como mensaje de WhatsApp vía Twilio.",
   flow:[["Webhook","trigger"],["WhatsApp","comms"]],creds:["twilioApi"],
   uses:["Alertas críticas al móvil","Notificaciones de ventas","Avisos de sistemas"],
   obs:["Requiere número de Twilio con sandbox de WhatsApp activo","Cambia from (Twilio) y to (destino) en formato whatsapp:+...","Fuerte para alertas de los flujos DevOps (07)"],
   tags:["whatsapp","twilio","alertas","webhook","comunicacion"]},

  // ---------- 04 · Datos / Scraping ----------
  {cat:"04-Datos-Scraping",name:"Datos · Agregador RSS a Telegram",file:"RSS-Agregador-Telegram",
   desc:"Lee un feed RSS periódicamente y publica cada novedad en un canal de Telegram.",
   flow:[["RSS Feed","trigger"],["Limpiar","data"],["Telegram","comms"]],creds:["telegramApi"],
   uses:["Vigilancia de noticias","Curación de contenido","Alertas de blogs"],
   obs:["El trigger RSS solo emite ítems nuevos","Cambia la URL del feed por la tuya","Agrega varios feeds con múltiples nodos RSS"],
   tags:["rss","telegram","noticias","scraping","contenido"]},
  {cat:"04-Datos-Scraping",name:"Datos · Scraper Web a Sheets",file:"Scraper-Web-a-Sheets",
   desc:"Descarga una página HTML cada 6h, extrae contenido por selectores CSS y lo guarda en Sheets.",
   flow:[["Cada 6h","trigger"],["Descargar","data"],["Extraer","data"],["Sheets","data"]],creds:["googleSheetsOAuth2"],
   uses:["Monitoreo de listados","Extracción de catálogos","Seguimiento de cambios"],
   obs:["Ajusta los cssSelector (.product-title) a la web real","Respeta robots.txt y términos del sitio","Para webs con JS usa un nodo de browser/Playwright"],
   tags:["scraping","html","sheets","css","datos"]},
  {cat:"04-Datos-Scraping",name:"Datos · Monitor de Precios",file:"Monitor-Precios-Alerta",
   desc:"Consulta un precio cada hora y alerta por Telegram cuando baja de un umbral.",
   flow:[["Cada Hora","trigger"],["Consultar","data"],["Bajo Umbral?","logic"],["Telegram","comms"]],creds:["telegramApi"],
   uses:["Alertas de ofertas","Seguimiento de competencia","Trading básico"],
   obs:["Cambia el umbral (100) en el nodo IF","Adapta la URL y el campo precio a tu API/web","Guarda histórico en Sheets para analizar tendencias"],
   tags:["precios","monitor","alerta","telegram","scraping"]},
  {cat:"04-Datos-Scraping",name:"Datos · Procesamiento de CSV",file:"Procesamiento-CSV",
   desc:"Lee un CSV local, lo parsea, agrega totales por categoría con JavaScript y vuelca el resumen a Sheets.",
   flow:[["Leer CSV","trigger"],["Parsear","data"],["Agregar","logic"],["Sheets","data"]],creds:["googleSheetsOAuth2"],
   uses:["Reportes de ventas","Consolidación de datos","ETL ligero"],
   obs:["Ajusta la ruta C:/datos/ventas.csv","El Code agrega por campo categoria/monto","Ideal para procesos batch nocturnos"],
   tags:["csv","procesamiento","etl","sheets","datos"]},
  {cat:"04-Datos-Scraping",name:"Datos · Sync Postgres a API",file:"Sync-Postgres-API",
   desc:"Cada 15 min consulta registros recientes en Postgres y los envía a una API externa.",
   flow:[["Cada 15min","trigger"],["Postgres","data"],["Enviar API","action"]],creds:["postgres","httpHeaderAuth"],
   uses:["Sincronización de CRM","Réplica de datos","Integración con SaaS"],
   obs:["La query filtra por actualizado_en < 15 min (incremental)","Requiere esa columna de timestamp en tu tabla","Usa autenticación por header para la API destino"],
   tags:["postgres","sync","api","sql","datos"]},

  // ---------- 05 · Productividad ----------
  {cat:"05-Productividad",name:"Productividad · Recordatorios de Calendar",file:"Calendar-Recordatorios",
   desc:"Cada 30 min revisa los eventos de la próxima hora en Google Calendar y los recuerda por Telegram.",
   flow:[["Cada 30min","trigger"],["Proximos","data"],["Telegram","comms"]],creds:["googleCalendarOAuth2","telegramApi"],
   uses:["Recordatorios de reuniones","Avisos de agenda","Gestión del tiempo"],
   obs:["La ventana timeMin/timeMax es de 1 hora","Puede duplicar avisos: añade dedupe con una hoja de enviados","Cambia el canal de aviso a Slack/Discord si prefieres"],
   tags:["calendar","recordatorios","telegram","productividad"]},
  {cat:"05-Productividad",name:"Productividad · Sync Trello a Notion",file:"Trello-a-Notion",
   desc:"Cuando se crea una tarjeta en Trello, la replica como página en una base de datos de Notion.",
   flow:[["Trello Trigger","trigger"],["Nueva Tarjeta?","logic"],["Notion","data"]],creds:["trelloApi","notionApi"],
   uses:["Unificar gestores de tareas","Archivo en Notion","Reporting centralizado"],
   obs:["Filtra solo eventos createCard","Reemplaza TU_DATABASE_ID","El trigger de Trello requiere configurar el webhook en Trello"],
   tags:["trello","notion","sync","tareas","productividad"]},
  {cat:"05-Productividad",name:"Productividad · Backup Sheets a Drive",file:"Backup-Sheets-Drive",
   desc:"Cada día a las 2am exporta una hoja a CSV y la sube a una carpeta de Google Drive.",
   flow:[["Cada Dia","trigger"],["Leer Sheets","data"],["A CSV","data"],["Drive","data"]],creds:["googleSheetsOAuth2","googleDriveOAuth2"],
   uses:["Copias de seguridad","Histórico de datos","Archivo diario"],
   obs:["Crea la carpeta Backups en Drive","El nombre incluye fecha (backup_yyyyLLdd.csv)","Programa en horario de baja actividad"],
   tags:["backup","sheets","drive","csv","productividad"]},
  {cat:"05-Productividad",name:"Productividad · Gestor de Tareas IA en Notion",file:"Gestor-Tareas-IA-Notion",
   desc:"Recibe una descripción por webhook, la IA la estructura (título, prioridad, horas) y crea la tarea en Notion.",
   flow:[["Webhook","trigger"],["Estructurar IA","ai"],["Notion","data"]],creds:["openAiApi","notionApi"],
   uses:["Captura rápida de tareas","Planificación asistida"," Inbox unificado"],
   obs:["response_format json_object para salida fiable","Mapea prioridad/estimado a propiedades de Notion","Dispara desde un bot de Telegram o un formulario"],
   tags:["ia","notion","tareas","openai","productividad"]},

  // ---------- 06 · Redes Sociales ----------
  {cat:"06-Redes-Sociales",name:"Redes · Bot de Telegram con Comandos",file:"Telegram-Bot-Comandos",
   desc:"Bot de Telegram que responde a comandos (/start, /help, /hora) procesados con JavaScript.",
   flow:[["Telegram Trigger","trigger"],["Procesar","logic"],["Responder","comms"]],creds:["telegramApi"],
   uses:["Bots de utilidad","Asistentes internos","Interfaz de automatizaciones"],
   obs:["Añade comandos en el nodo Code","Base para conectar cualquier flujo n8n vía chat","Configura los comandos en @BotFather"],
   tags:["telegram","bot","comandos","chat","redes"]},
  {cat:"06-Redes-Sociales",name:"Redes · Notificaciones a Discord",file:"Discord-Notificaciones",
   desc:"Recibe un evento por webhook y lo publica en un canal de Discord usando un webhook URL.",
   flow:[["Webhook","trigger"],["Discord","comms"]],creds:[],
   uses:["Alertas de comunidad","Logs en Discord","Avisos de builds"],
   obs:["Usa autenticación por webhook (no necesita bot)","Reemplaza TU_DISCORD_WEBHOOK_URL","Soporta markdown de Discord en el contenido"],
   tags:["discord","webhook","notificaciones","comunidad","redes"]},
  {cat:"06-Redes-Sociales",name:"Redes · Publicar en LinkedIn desde Sheets",file:"Publicar-LinkedIn-Sheets",
   desc:"Cada día lee posts pendientes de una hoja y los publica en LinkedIn, filtrando por estado.",
   flow:[["Cada Dia","trigger"],["Leer Posts","data"],["Pendiente?","logic"],["LinkedIn","comms"]],creds:["linkedInOAuth2","googleSheetsOAuth2"],
   uses:["Calendario de contenidos LinkedIn","Publicación programada","Gestión editorial"],
   obs:["Marca estado=pendiente en la hoja; cámbialo a publicado tras enviar","Requiere permisos de LinkedIn (w_member_social)","Combina con 01-IA para generar los posts"],
   tags:["linkedin","sheets","publicar","contenido","redes"]},
  {cat:"06-Redes-Sociales",name:"Redes · Programador con Buffer",file:"Buffer-Programador",
   desc:"Detecta emails con la etiqueta [publicar] y programa su contenido en redes vía Buffer.",
   flow:[["Gmail Trigger","trigger"],["Tiene Tag?","logic"],["Buffer","comms"]],creds:["gmailOAuth2","bufferApi"],
   uses:["Programar contenido por email","Cola de publicaciones","Aprobación editorial"],
   obs:["Reemplaza TU_PROFILE_ID de Buffer","El asunto debe contener [publicar]","Buffer soporta múltiples redes a la vez"],
   tags:["buffer","gmail","programar","redes","contenido"]},

  // ---------- 07 · DevOps ----------
  {cat:"07-DevOps",name:"DevOps · Monitor de Uptime",file:"Monitor-Uptime-Servidores",
   desc:"Cada 5 min hace ping HTTP a una lista de servidores y alerta por Telegram si alguno no responde.",
   flow:[["Cada 5min","trigger"],["Lista","data"],["Ping HTTP","action"],["Alertar","comms"]],creds:["telegramApi"],
   uses:["Vigilancia de disponibilidad","Alertas de caída","SLA básico"],
   obs:["Edita la lista de URLs en el nodo Set","onError=continueErrorOutput envía los fallos a la rama de alerta","Añade reintentos para evitar falsos positivos"],
   tags:["devops","uptime","monitor","alerta","telegram"]},
  {cat:"07-DevOps",name:"DevOps · GitHub Webhook a Slack",file:"GitHub-Webhook-Slack",
   desc:"Escucha eventos push de GitHub y notifica en Slack con repo, autor y mensaje del commit.",
   flow:[["Webhook GitHub","trigger"],["Es Push?","logic"],["Slack","comms"]],creds:["slackApi"],
   uses:["Visibilidad de despliegues","Actividad del repo","Cultura DevOps"],
   obs:["Filtra por header x-github-event = push","Configura el webhook en GitHub Settings","Extiende a pull_request, issues, releases"],
   tags:["devops","github","slack","webhook","ci"]},
  {cat:"07-DevOps",name:"DevOps · Monitor de Certificados SSL",file:"Monitor-SSL-Certs",
   desc:"Cada día comprueba los días restantes de un certificado SSL y alerta si faltan menos de 30.",
   flow:[["Cada Dia","trigger"],["Consultar SSL","data"],["Por Expirar?","logic"],["Telegram","comms"]],creds:["telegramApi"],
   uses:["Evitar caídas por SSL vencido","Renovación proactiva","Auditoría de dominios"],
   obs:["Usa una API de check SSL o un nodo Code con tls","Umbral de 30 días ajustable en el IF","Monitorea varios dominios con un loop"],
   tags:["devops","ssl","certificados","monitor","alerta"]},
  {cat:"07-DevOps",name:"DevOps · Alerta de Errores",file:"Alerta-Errores-Slack",
   desc:"Recibe logs por webhook, filtra los de nivel error y los publica en un canal de alertas de Slack.",
   flow:[["Webhook Error","trigger"],["Nivel Error?","logic"],["Slack","comms"],["Confirmar","action"]],creds:["slackApi"],
   uses:["Centralización de errores","Alertado tipo Sentry","Observabilidad"],
   obs:["Filtra por body.level = error","Incluye stacktrace en el mensaje","Responde 200 al final para que el emisor no reintente"],
   tags:["devops","errores","slack","logs","alerta"]},

  // ---------- 08 · Marketing ----------
  {cat:"08-Marketing",name:"Marketing · Captura y Enriquecimiento de Leads",file:"Lead-Capture-Enrichment",
   desc:"Recibe un lead por webhook, la IA lo puntúa y enriquece, lo guarda en Sheets y avisa a ventas.",
   flow:[["Webhook Lead","trigger"],["Enriquecer IA","ai"],["Guardar","data"],["Avisar","comms"]],creds:["openAiApi","googleSheetsOAuth2","telegramApi"],
   uses:["Lead scoring automático","Enriquecimiento de datos","Alerta a comerciales"],
   obs:["La IA devuelve score/sector/mensaje en JSON","Puntúa 0-100 para priorizar seguimiento","Conecta la entrada con 02-Webhooks (formularios)"],
   tags:["marketing","leads","ia","scoring","crm"]},
  {cat:"08-Marketing",name:"Marketing · Sync Suscriptores a Mailchimp",file:"Mailchimp-Sync-Suscriptores",
   desc:"Cada 12h lee suscriptores de Sheets y los sincroniza (upsert) a una lista de Mailchimp.",
   flow:[["Cada 12h","trigger"],["Leer Lista","data"],["Mailchimp","action"]],creds:["mailchimpApi","googleSheetsOAuth2"],
   uses:["Sincronización de audiencias","Altas automáticas","Mantenimiento de listas"],
   obs:["Reemplaza TU_LIST_ID de Mailchimp","upsert evita duplicados por email","Mapea merge fields (FNAME) según tu lista"],
   tags:["marketing","mailchimp","sheets","sync","email"]},
  {cat:"08-Marketing",name:"Marketing · CRM HubSpot desde Formulario",file:"HubSpot-CRM-Formulario",
   desc:"Recibe datos de un formulario por webhook, los mapea y crea un contacto en HubSpot.",
   flow:[["Webhook Form","trigger"],["Mapear","data"],["HubSpot","action"]],creds:["hubspotApi"],
   uses:["Captura de leads a CRM","Sincronización de formularios","Pipeline comercial"],
   obs:["Mapea email/firstname/company a propiedades de HubSpot","Añade más campos según tu objeto contacto","Combina con 08 Lead-Enrichment para scoring"],
   tags:["marketing","hubspot","crm","formulario","leads"]},
  {cat:"08-Marketing",name:"Marketing · Follow-up de Webinar",file:"Webinar-Followup",
   desc:"Registra asistentes a un webinar, espera 1 día y envía un email de seguimiento con la grabación.",
   flow:[["Webhook","trigger"],["Registrar","data"],["Esperar 1 dia","wait"],["Email","comms"]],creds:["googleSheetsOAuth2","smtp"],
   uses:["Nurturing post-evento","Envío de grabaciones","Conversión de asistentes"],
   obs:["El nodo Wait pausa la ejecución 1 día (n8n debe estar activo)","Guarda asistentes en Sheets para métricas","Personaliza el HTML con nombre y recursos"],
   tags:["marketing","webinar","followup","email","nurturing"]},

  // ---------- 09 · Industrial / Plantas (Oil&Gas, minería, desaladoras, metalúrgicas, refinerías, maestranzas) ----------
  {cat:"09-Industrial-Plantas",name:"Industrial · Checklist de Inspección",file:"Checklist-Inspeccion-Equipos",
   desc:"Recibe un checklist de inspección de equipos (ronda), calcula % de cumplimiento y alerta al supervisor si hay fallas.",
   flow:[["Webhook Checklist","trigger"],["Evaluar","logic"],["Registrar","data"],["Con Fallas?","logic"],["Alertar Supervisor","comms"]],creds:["googleSheetsOAuth2","telegramApi"],
   uses:["Rondas de operación","Inspección pre-uso de equipos","Control de calidad en línea","Verificación de maestranza"],
   obs:["El body trae items:[{nombre,ok}] y se calcula cumplimiento","Alerta solo si hay ítems reprobados","Aplica a Oil&Gas, minería, refinerías y maestranzas por igual"],
   tags:["industrial","checklist","inspeccion","ronda","hse","oilgas","mineria"]},
  {cat:"09-Industrial-Plantas",name:"Industrial · Bitácora de Operadores",file:"Bitacora-Operadores",
   desc:"Sella cada anotación de bitácora con fecha/turno/operador, la guarda y escala a jefatura si el tipo es 'alerta'.",
   flow:[["Webhook Bitacora","trigger"],["Sellar","data"],["Guardar","data"],["Es Alerta?","logic"],["Avisar Jefatura","comms"]],creds:["googleSheetsOAuth2","telegramApi"],
   uses:["Bitácora de sala de control","Registro de eventos por turno","Trazabilidad operativa","Libro de novedades"],
   obs:["Reemplaza el spreadsheet de Bitácora","tipo=alerta dispara el aviso inmediato","Base para el handover de cambio de turno"],
   tags:["industrial","bitacora","operadores","turno","trazabilidad","sala-control"]},
  {cat:"09-Industrial-Plantas",name:"Industrial · Cambio de Turno (Handover)",file:"Cambio-Turno-Handover",
   desc:"En cada cambio de turno lee la bitácora y la IA redacta el reporte de entrega: eventos, pendientes críticos y acciones.",
   flow:[["Cambios de Turno","trigger"],["Leer Pendientes","data"],["Resumir IA","ai"],["Enviar Handover","comms"]],creds:["googleSheetsOAuth2","openAiApi","telegramApi"],
   uses:["Entrega de guardia","Comunicación entre turnos","Resumen ejecutivo de operación","Pase de pendientes"],
   obs:["Programa a las horas reales de cambio (ej 07/15/23)","La IA resume y prioriza pendientes críticos","Se alimenta de la Bitácora de Operadores"],
   tags:["industrial","handover","cambio-turno","ia","entrega","operacion"]},
  {cat:"09-Industrial-Plantas",name:"Industrial · Cuadro de Turnos Rotativos",file:"Cuadro-Turnos-Rotativos",
   desc:"Genera automáticamente la rotación de equipos por turnos (ej 4x3) y la publica en Sheets notificando a los equipos.",
   flow:[["Cada Lunes","trigger"],["Generar Rotación","logic"],["Publicar Cuadro","data"],["Notificar Equipos","comms"]],creds:["googleSheetsOAuth2","telegramApi"],
   uses:["Programación de cuadrillas","Rotación 4x3 / 7x7","Gestión de turnos mineros","Planificación de maestranza"],
   obs:["Ajusta el patrón de rotación en el nodo Code","Equipa los nombres de equipos y turnos reales","Se publica semanalmente; adapta la frecuencia"],
   tags:["industrial","cuadro-turnos","rotacion","cuadrillas","planificacion","mineria"]},
  {cat:"09-Industrial-Plantas",name:"Industrial · Inspección de Seguridad HSE",file:"Inspeccion-Seguridad-HSE",
   desc:"Registra hallazgos de inspección HSE, aplica matriz de riesgo (probabilidad × consecuencia) y alerta si el riesgo es crítico.",
   flow:[["Webhook Inspección","trigger"],["Matriz Riesgo","logic"],["Registrar","data"],["Riesgo Crítico?","logic"],["Alertar HSE","comms"]],creds:["googleSheetsOAuth2","telegramApi"],
   uses:["Inspecciones de seguridad","Matriz de riesgos 3x3 / 5x5","Auditorías HSE","Observaciones preventivas"],
   obs:["probabilidad/consecuencia en {bajo,medio,alto} → riesgo 1-9","CRITICO (≥6) dispara acción inmediata","Cumple con estándares de refinerías y minería"],
   tags:["industrial","hse","seguridad","matriz-riesgo","inspeccion","oilgas","refineria"]},
  {cat:"09-Industrial-Plantas",name:"Industrial · Permiso de Trabajo (PTW)",file:"Permiso-Trabajo-Peligroso",
   desc:"Folía una solicitud de permiso de trabajo peligroso (caliente/altura/espacio confinado) y la envía al aprobador HSE.",
   flow:[["Solicitud Permiso","trigger"],["Foliar","data"],["Registrar","data"],["Notificar Aprobador","comms"]],creds:["googleSheetsOAuth2","telegramApi"],
   uses:["Permisos de trabajo en caliente","Trabajo en altura","Espacios confinados","Control de contratistas"],
   obs:["Genera folio único PTW-fecha-hora","Estado inicial PENDIENTE_APROBACION","Flujo clave en paradas de planta y mantenimiento"],
   tags:["industrial","ptw","permiso-trabajo","hse","trabajo-peligroso","parada"]},
  {cat:"09-Industrial-Plantas",name:"Industrial · Reporte de Incidente SST",file:"Incidente-SST",
   desc:"Registra incidentes de seguridad y salud, clasifica severidad y escala a gerencia si supera primer auxilio.",
   flow:[["Reportar Incidente","trigger"],["Clasificar","logic"],["Registrar","data"],["Escalar?","logic"],["Escalar Gerencia","comms"]],creds:["googleSheetsOAuth2","telegramApi"],
   uses:["Reporte de accidentes","Casi-accidentes (near miss)","Investigación de incidentes","Indicadores SST"],
   obs:["severidad en {menor,primer_auxilio,incapacitante,fatal}","Se escala desde primer_auxilio en adelante","Alimenta tasas de frecuencia/gravedad"],
   tags:["industrial","sst","incidente","seguridad","escalado","hse"]},
  {cat:"09-Industrial-Plantas",name:"Industrial · Orden de Trabajo Maestranza",file:"Orden-Trabajo-Maestranza",
   desc:"Genera y folía una orden de trabajo de maestranza por falla reportada, con prioridad, y avisa a la cuadrilla.",
   flow:[["Nueva OT","trigger"],["Generar OT","data"],["Registrar OT","data"],["Avisar Maestranza","comms"]],creds:["googleSheetsOAuth2","telegramApi"],
   uses:["Mantenimiento correctivo","Gestión de maestranza","Seguimiento de fallas","Backlog de taller"],
   obs:["Folio OT-fecha-hora y estado ABIERTA","prioridad en {baja,media,alta,urgente}","Conecta con Control de Calibración para OT preventivas"],
   tags:["industrial","maestranza","orden-trabajo","mantenimiento","taller","cmms"]},
  {cat:"09-Industrial-Plantas",name:"Industrial · Alarmas SCADA a Sala de Control",file:"Alarmas-SCADA-Sala-Control",
   desc:"Lee tags críticos (OPC/Modbus) cada minuto, evalúa límites de ingeniería (HH/H/L/LL) y notifica alarmas a sala de control.",
   flow:[["Lectura SCADA","trigger"],["Leer Tags","data"],["Evaluar Alarmas","logic"],["Hay Alarma?","logic"],["Registrar","data"],["Notificar Sala","comms"]],creds:["httpHeaderAuth","googleSheetsOAuth2","telegramApi"],
   uses:["Monitoreo de variables críticas","Gestión de alarmas","Desaladoras y plantas de proceso","Supervisión remota"],
   obs:["Adapta la URL del servidor OPC/bridge a tu SCADA","Cada tag trae valor, H, HH, L, LL y unidad","Registra historial de alarmas para análisis posterior"],
   tags:["industrial","scada","alarmas","opc","modbus","sala-control","desaladora","oilgas"]},
  {cat:"09-Industrial-Plantas",name:"Industrial · Reporte de Producción con IA",file:"Reporte-Produccion-IA",
   desc:"Al cierre de turno lee los KPIs y la IA redacta el reporte diario: producción vs meta, OEE, desviaciones y acciones.",
   flow:[["Cierre de Turno","trigger"],["Leer KPIs","data"],["Analizar IA","ai"],["Enviar Reporte","comms"]],creds:["googleSheetsOAuth2","openAiApi","telegramApi"],
   uses:["Reporte diario de planta","Seguimiento de OEE","Cierre de producción metalúrgica","Indicadores de refinería"],
   obs:["Alimenta la hoja KPI_Producción con los datos del día","La IA propone 3 acciones correctivas","Programa al cierre del último turno"],
   tags:["industrial","produccion","kpi","oee","ia","reporte","metalurgia","refineria"]},
  {cat:"09-Industrial-Plantas",name:"Industrial · Control de Calibración",file:"Control-Calibracion-Instrumentos",
   desc:"Revisa a diario los instrumentos y alerta los vencidos o por vencer (≤15 días) para generar OT de calibración.",
   flow:[["Revisión Diaria","trigger"],["Consultar","data"],["Filtrar Vencimientos","logic"],["Hay Vencimientos?","logic"],["Ordenar Calibración","comms"]],creds:["googleSheetsOAuth2","telegramApi"],
   uses:["Plan de calibración","Gestión de instrumentación","Cumplimiento ISO 9001","Mantenimiento preventivo"],
   obs:["La hoja Instrumentos debe tener proxima_calibración","Distingue vencido (dias<0) de por vencer","Encadena con Orden de Trabajo Maestranza"],
   tags:["industrial","calibracion","instrumentos","metrologia","preventivo","iso"]},
  {cat:"09-Industrial-Plantas",name:"Industrial · Parada y Arranque de Planta",file:"Parada-Arranque-Checklist",
   desc:"Valida el checklist pre-arranque/parada: si todo está OK libera la operación, si no la bloquea y lista los pendientes.",
   flow:[["Solicitud Parada","trigger"],["Validar Checklist","logic"],["Todo OK?","logic"],["Liberar / Bloquear","comms"],["Registrar","data"]],creds:["googleSheetsOAuth2","telegramApi"],
   uses:["Procedimiento de arranque seguro","Parada de unidades","Verificación pre-startup","PSSR de seguridad"],
   obs:["checklist:[{paso,ok}] — todos deben estar OK para liberar","Bloquea con lista de pendientes si falta algo","Crítico en refinerías y plantas químicas"],
   tags:["industrial","parada","arranque","checklist","pssr","seguridad","refineria"]},
];
