#!/usr/bin/env node
/**
 * gen-200.js — Genera plantillas de n8n Workflow Templates
 * Formato seguro: cada plantilla en una linea con campos separados por |
 */
const fs=require('fs'),path=require('path');
const base=__dirname;

// Parser: convierte linea pipe-separated a objeto
function T(s){
  const p=s.split('|');
  return {
    cat:p[0], name:p[1], file:p[2], desc:p[3],
    flow:p[4].split(';').map(x=>{const a=x.split('^');return[a[0],a[1]]}),
    creds:p[5]?p[5].split(',').filter(Boolean):[],
    uses:p[6]?p[6].split(','):['Uso general'],
    obs:p[7]?p[7].split(','):['Configura credenciales antes de activar'],
    tags:p[8]?p[8].split(','):['general']
  };
}

const RAW = [
// 01-IA-AI
"01-IA-AI|IA · Agente con Memoria|IA-Agente-Memoria|Agente conversacional que recuerda contexto entre mensajes y mantiene historial persistente.|Webhook^webhook;Historial^sheetsRead;Agente IA^ai;Guardar Contexto^sheets;Responder^respond|openAiApi,googleSheetsOAuth2|Chatbot con memoria,Asistente virtual persistente,Soporte tecnico con contexto|Guarda historial en Sheets para persistencia,El IA incluye contexto previo en el prompt,Ideal para bots de soporte 24/7|ia,agente,memoria,chatbot,openai",
"01-IA-AI|IA · Chat con PDF|IA-Chat-PDF|Sube un PDF, extrae el texto y conversa con el documento en lenguaje natural.|Subir PDF^formTrg;Extraer Texto^code;Responder IA^ai;Enviar Respuesta^respond|openAiApi|Consulta de documentos,Analisis de contratos,Estudio de manuales|Extrae texto con Code o ExtractFromFile,El IA responde basandose en el contenido,Para PDFs escaneados necesita OCR|ia,pdf,chat,documentos,rag",
"01-IA-AI|IA · Analisis de Imagenes|IA-Analisis-Imagenes|Analiza imagenes con vision por computadora: describe contenido, detecta objetos y extrae texto.|Webhook^webhook;Analizar IA^ai;Resultado^respond|openAiApi|Descripcion automatica de imagenes,Moderacion de contenido,Deteccion de defectos visuales|Usa gpt-4o con capacidad de vision,Envia imagen como base64 o URL,Aplicable a control de calidad visual|ia,vision,imagenes,ocr,openai",
"01-IA-AI|IA · Pipeline de Traduccion|IA-Pipeline-Traduccion|Traduce contenido en cadena a multiples idiomas manteniendo formato y contexto tecnico.|Webhook^webhook;Detectar Idioma^code;Traducir IA^ai;Guardar^sheets;Responder^respond|openAiApi,googleSheetsOAuth2|Localizacion de productos,Documentacion multilingue,Subtitulos de videos|Detecta idioma origen antes de traducir,Mantiene terminologia tecnica,Procesa lotes para eficiencia|ia,traduccion,multiidioma,localizacion,openai",
"01-IA-AI|IA · Generador de Codigo|IA-Generador-Codigo|Asistente que genera codigo a partir de descripciones en lenguaje natural en Python, JS, SQL.|Webhook^webhook;Generar IA^ai;Formatear^code;Responder^respond|openAiApi|Prototipado rapido,Aprendizaje de programacion,Generacion de scripts|Especifica el lenguaje en el prompt,Incluye comentarios explicativos,Valida el codigo antes de usarlo|ia,codigo,programacion,openai,dev",
"01-IA-AI|IA · Analisis de Contratos|IA-Analisis-Contratos|Analiza contratos legales: extrae clausulas clave, fechas, obligaciones y riesgos.|Webhook^webhook;Extraer IA^ai;Estructurar^code;Guardar^sheets|openAiApi,googleSheetsOAuth2|Revision legal automatizada,Auditoria de contratos,Gestion de proveedores|El IA devuelve JSON estructurado,Detecta clausulas abusivas o inusuales,Complementa no reemplaza revision legal|ia,legal,contratos,extraccion,openai",
"01-IA-AI|IA · Parser de Curriculums|IA-Parser-CV|Extrae datos estructurados de CVs en PDF/Word: experiencia, educacion, skills, contacto.|Webhook^webhook;Extraer IA^ai;Normalizar^code;Guardar BD^sheets|openAiApi,googleSheetsOAuth2|Procesamiento masivo de CVs,Filtrado automatico de candidatos,Base de talento|Convierte CVs no estructurados a JSON,Normaliza fechas y cargos,Integra con tu ATS|ia,cv,rrhh,parser,reclutamiento",
"01-IA-AI|IA · Resumen de Reuniones|IA-Resumen-Reuniones|Transcribe y resume reuniones: extrae decisiones, action items y responsables.|Audio^formTrg;Transcribir^ai;Resumir IA^ai;Enviar^email|openAiApi|Minutas automaticas,Seguimiento de action items,Onboarding de ausentes|Usa Whisper para transcripcion,Identifica responsables y plazos,Envia resumen por email|ia,reuniones,transcripcion,whisper,resumen",
"01-IA-AI|IA · Detector de Phishing|IA-Detector-Phishing|Analiza emails sospechosos con IA para detectar intentos de phishing y fraude.|Email^gmailTrg;Analizar IA^ai;Es Phishing?^if;Alertar^telegram;Marcar^set|gmailOAuth2,openAiApi,telegramApi|Seguridad email corporativo,Filtro anti-fraude,Concienciacion de seguridad|El IA evalua remitente asunto y enlaces,Alerta al equipo de seguridad,No reemplaza al firewall corporativo|ia,seguridad,phishing,email,openai",
"01-IA-AI|IA · Asistente de Investigacion|IA-Asistente-Investigacion|Recopila informacion de multiples fuentes, la sintetiza y genera un informe estructurado.|Buscar^http;Analizar IA^ai;Compilar^code;Informe^email|openAiApi|Investigacion de mercado,Analisis competitivo,Estudios tecnicos|Agrega datos de varias APIs,El IA produce informe con secciones,Programa ejecuciones periodicas|ia,investigacion,analisis,informe,openai",
"01-IA-AI|IA · Clasificador de Tickets|IA-Clasificador-Tickets|Clasifica automaticamente tickets de soporte por categoria, urgencia y departamento.|Webhook^webhook;Clasificar IA^ai;Enrutar^code;Asignar^sheets;Notificar^slack|openAiApi,googleSheetsOAuth2,slackApi|Soporte tecnico automatizado,Helpdesk inteligente,Gestion de incidencias|El IA asigna categoria y prioridad,Redirige al departamento correcto,Reduce tiempo de primera respuesta|ia,tickets,soporte,helpdesk,openai",
"01-IA-AI|IA · Generador de Descripciones|IA-Generador-Descripciones|Crea descripciones de productos optimizadas para SEO a partir de datos basicos.|Producto^webhook;Generar IA^ai;Guardar^sheets;Publicar^http|openAiApi,googleSheetsOAuth2|E-commerce,Catalogos online,Marketplace|Incluye keywords SEO en el prompt,Genera titulo mas descripcion,Procesa catalogos en lote|ia,ecommerce,seo,productos,openai",
"01-IA-AI|IA · Limpieza de Datos con IA|IA-Limpieza-Datos|Detecta y corrige automaticamente errores, duplicados e inconsistencias en datasets.|Datos^sheetsRead;Analizar IA^ai;Limpiar^code;Guardar^sheets|googleSheetsOAuth2,openAiApi|Limpieza de CRMs,Normalizacion de bases,Calidad de datos|El IA identifica duplicados,Normaliza nombres emails y telefonos,Reporta que se corrigio|ia,datos,limpieza,calidad,openai",
"01-IA-AI|IA · Texto a Voz TTS|IA-Texto-Voz-TTS|Convierte texto a audio natural con voces de OpenAI TTS para accesibilidad y contenido.|Texto^webhook;Generar Audio^ai;Guardar^drive;URL Audio^respond|openAiApi|Audiolibros,Accesibilidad visual,Contenido multimedia|Usa el endpoint audio speech,Voces: alloy echo fable onyx,Modelo tts-1 o tts-1-hd|ia,tts,audio,voz,openai",
"01-IA-AI|IA · Analisis de Resenas|IA-Analisis-Resenas|Agrega resenas de productos y la IA extrae pros, contras y puntuacion promedio.|Resenas^http;Analizar IA^ai;Dashboard^sheets;Alertas Negativas^telegram|openAiApi,googleSheetsOAuth2,telegramApi|Monitoreo de reputacion,Product feedback,Analisis competitivo|Agrega resenas de multiples fuentes,El IA clasifica sentimiento,Alerta si hay resenas muy negativas|ia,resenas,sentimiento,producto,openai",
"01-IA-AI|IA · Respuestas FAQ Inteligentes|IA-Respuestas-FAQ|Bot que responde preguntas frecuentes basandose en una base de conocimiento documentada.|Pregunta^webhook;Buscar Docs^sheetsRead;Responder IA^ai;Enviar^respond|openAiApi,googleSheetsOAuth2|Soporte automatizado,Onboarding de empleados,Bot de ayuda interna|Carga documentos como contexto,El IA busca respuesta mas relevante,Aprende de nuevas preguntas|ia,faq,soporte,chatbot,rag",
"01-IA-AI|IA · Optimizador de Prompts|IA-Optimizador-Prompts|Analiza y mejora prompts de IA para obtener mejores resultados.|Prompt^webhook;Optimizar IA^ai;Comparar^code;Resultado^respond|openAiApi|Ingenieria de prompts,Mejora de resultados IA,Educacion en IA|El IA reescribe el prompt anadiendo claridad,Sugiere variaciones y tecnicas,Util para equipos que usan IA|ia,prompts,optimizacion,openai",
"01-IA-AI|IA · Analizador de Gastos|IA-Analizador-Gastos|Extrae datos de recibos y facturas con IA: importe, fecha, categoria, IVA.|Recibo^formTrg;Extraer IA^ai;Categorizar^code;Guardar^sheets;Resumen Mensual^email|openAiApi,googleSheetsOAuth2|Gestion de gastos corporativos,Contabilidad automatizada,Reportes de viaticos|El IA lee el recibo desde imagen,Categoriza automaticamente,Genera resumen mensual|ia,gastos,contabilidad,ocr,openai",
"01-IA-AI|IA · Detector de Plagio IA|IA-Detector-Plagio|Analiza si un texto fue generado por IA o escrito por un humano.|Texto^webhook;Analizar IA^ai;Veredicto^respond|openAiApi|Academia,Control de calidad editorial,Verificacion de contenido original|El IA evalua patrones de texto generado,No es 100% infalible,Combina con herramientas especializadas|ia,plagio,deteccion,academia,openai",
"01-IA-AI|IA · Generador de SQL|IA-Generador-SQL|Convierte preguntas en lenguaje natural a consultas SQL optimizadas.|Pregunta^webhook;Generar SQL^ai;Ejecutar^postgres;Resultado^respond|openAiApi,postgres|Analisis de datos sin codigo,Reporting automatico,Exploracion de BD|Especifica el esquema de tu BD,El IA genera SELECT seguro,Valida la consulta antes de ejecutar|ia,sql,base-datos,openai,postgres",
"01-IA-AI|IA · Moderador de Contenido|IA-Moderador-Contenido|Filtra y modera automaticamente comentarios posts y mensajes con criterios personalizables.|Comentario^webhook;Moderar IA^ai;Es Apropiado?^if;Publicar^http;Ocultar^http|openAiApi|Moderacion de comunidad,Filtro de comentarios,Gestion de foros|Define criterios spam insultos of-topic,El IA devuelve aprobado y motivo,Mantiene log de moderacion|ia,moderacion,comunidad,filtro,openai",
"01-IA-AI|IA · Recomendador Personalizado|IA-Recomendador|Genera recomendaciones personalizadas basadas en el historial del usuario.|Usuario^webhook;Historial^sheetsRead;Recomendar IA^ai;Enviar^respond|openAiApi,googleSheetsOAuth2|E-commerce,Streaming,Contenido personalizado|Combina historial y preferencias,El IA sugiere contenido relevante,Mejora con retroalimentacion|ia,recomendacion,personalizacion,ecommerce,openai",
"01-IA-AI|IA · Diagrama de Texto|IA-Diagrama-Texto|Convierte descripciones de procesos en texto a diagramas Mermaid visuales.|Descripcion^webhook;Generar IA^ai;Mermaid^respond;Guardar^sheets|openAiApi,googleSheetsOAuth2|Documentacion tecnica,Diagramas de proceso,Modelado de flujos|El IA genera codigo Mermaid,Pega el output en mermaid.live,Util para diagramas UML|ia,diagrama,mermaid,documentacion,openai",
"01-IA-AI|IA · Resumen de Hilo de Email|IA-Resumen-Hilo-Email|Condensa hilos de email largos en un resumen con decisiones y pendientes.|Email^gmailTrg;Resumir IA^ai;Accion Requerida^code;Notificar^slack|gmailOAuth2,openAiApi,slackApi|Gestion de bandeja saturada,Seguimiento de proyectos,Onboarding de conversaciones|Identifica quien decidio que,Extrae action items con responsable,Reduce lectura de emails largos|ia,email,resumen,productividad,openai",
// 02-Webhooks-API
"02-Webhooks-API|API · Proxy Inverso|API-Proxy-Inverso|Proxy que recibe requests, las transforma y las reenvia a multiples APIs manteniendo logging.|Entrada^webhook;Transformar^code;Reenviar^http;Log^sheets;Responder^respond|googleSheetsOAuth2|Enrutamiento de APIs,Fachada de microservicios,Logging centralizado|Transforma headers y body antes de reenviar,Registra cada request,Implementa rate limiting|api,proxy,microservicios,routing,webhook",
"02-Webhooks-API|API · Retry con Backoff|API-Retry-Backoff|Reintenta llamadas HTTP fallidas con backoff exponencial hasta tener exito.|Schedule^schedule;Llamar API^http;Exito?^if;Esperar^wait;Reintentar^http;Notificar Fallo^telegram|telegramApi|Integraciones resilientes,Sync de APIs inestables,Procesamiento batch|Backoff exponencial 1s 2s 4s,Maximo reintentos configurable,Alerta tras agotar reintentos|api,retry,resiliencia,backoff,http",
"02-Webhooks-API|API · GraphQL Query|API-GraphQL-Query|Ejecuta queries GraphQL contra cualquier endpoint y normaliza la respuesta.|Trigger^schedule;Query GraphQL^http;Normalizar^code;Guardar^sheets|googleSheetsOAuth2|Consulta de APIs modernas,Sync con CMS headless,Integracion con Shopify GitHub|Usa POST con body GraphQL,Maneja errores y nulls,Paginacion con cursor|api,graphql,query,cms,http",
"02-Webhooks-API|API · Health Check|API-Health-Check|Monitorea el estado de multiples APIs y alerta si alguna cae o responde lento.|Cada 5min^schedule;Lista APIs^set;Check^code;Caida?^if;Alertar^telegram;OK^set|telegramApi|Monitoreo de microservicios,SLA de APIs,Observabilidad|Mide codigo HTTP y tiempo de respuesta,Umbral configurable,Mantiene historial|api,health-check,monitoreo,uptime,devops",
"02-Webhooks-API|API · Verificador de Webhooks|API-Verificador-Webhooks|Verifica firmas HMAC SHA de webhooks entrantes antes de procesarlos.|Webhook^webhook;Verificar Firma^code;Valido?^if;Procesar^set;Rechazar^respond||Seguridad de webhooks,Stripe GitHub verification,Anti-replay|Calcula HMAC con secret compartido,Compara con header de firma,Rechaza si no coincide|api,webhook,seguridad,hmac,firma",
"02-Webhooks-API|API · Agregador Multi-Endpoint|API-Agregador|Consolida datos de multiples APIs en una respuesta unificada.|Trigger^webhook;API 1^http;API 2^http;API 3^http;Fusionar^code;Responder^respond||Dashboards unificados,Consolidacion de datos,Reporting multi-fuente|Llama N APIs en paralelo,Fusiona resultados en JSON,Cachea respuestas|api,agregador,multi-endpoint,consolidacion,http",
"02-Webhooks-API|API · Cache HTTP|API-Cache-HTTP|Cachea respuestas de APIs para reducir latencia y coste con TTL configurable.|Request^webhook;En Cache?^code;Cache Hit^respond;Cache Miss^http;Guardar Cache^set;Responder^respond||Optimizacion de APIs,Reduccion de costes,Rate limit management|Usa cache o Sheets como store,TTL configurable,Invalida con webhook|api,cache,optimizacion,latencia,http",
"02-Webhooks-API|API · OAuth2 Token Refresher|API-OAuth2-Refresher|Renueva automaticamente tokens OAuth2 antes de que expiren.|Cada hora^schedule;Renovar Token^http;Guardar^set;Actualizar Credenciales^code;OK^set||Integraciones OAuth2,Google Microsoft APIs,Automatizacion segura|Usa refresh_token para nuevo access_token,Guarda el nuevo token,Ejecuta antes de expirar|api,oauth2,token,seguridad,http",
"02-Webhooks-API|API · Mock Server|API-Mock-Server|Sirve respuestas mock para testing de frontend e integraciones sin backend real.|Request^webhook;Ruta?^if;Mock A^set;Mock B^set;Mock C^set;Responder^respond||Testing de frontend,Prototipado de APIs,Desarrollo sin backend|Devuelve JSON mock segun ruta,Latencia simulable,Cambia respuestas con flag|api,mock,testing,desarrollo,webhook",
"02-Webhooks-API|API · Webhook a Multi Servicios|API-Webhook-Multi|Recibe un evento y lo distribuye a multiples servicios en paralelo fan-out.|Webhook^webhook;Procesar^code;Notificar Slack^slack;Guardar Sheets^sheets;Enviar Email^email;Confirmar^respond|slackApi,googleSheetsOAuth2|Distribucion de eventos,Integracion multi-canal,Arquitectura fan-out|Un evento a N destinos en paralelo,Cada destino tiene su logica,Confirma recepcion|api,webhook,fan-out,multi-canal,distribucion",
"02-Webhooks-API|API · Rate Limiter|API-Rate-Limiter|Limita la frecuencia de requests a una API para respetar cuotas y evitar bans.|Webhook^webhook;Contador^code;Limite?^if;Procesar^http;Rechazar 429^respond;Reset Contador^code||Proteccion de APIs,Respeto de cuotas,Anti-abuso|Cuenta requests por IP,Devuelve 429 si excede,Reset configurable|api,rate-limit,proteccion,cuota,webhook",
"02-Webhooks-API|API · Batch Processor|API-Batch-Processor|Agrupa requests individuales en lotes para procesarlos eficientemente.|Trigger^schedule;Leer Cola^sheetsRead;Agrupar^code;Procesar Lote^http;Resultado^sheets;Limpiar Cola^set|googleSheetsOAuth2|Procesamiento masivo,Optimizacion de APIs,ETL por lotes|Agrupa N items en una llamada,Reduce el numero de requests,Procesa lote cada X minutos|api,batch,procesamiento,optimizacion,lotes",
"02-Webhooks-API|API · Conversor de Formatos|API-Conversor-Formatos|Convierte entre JSON XML CSV YAML y otros formatos de datos.|Entrada^webhook;Detectar^code;Convertir^code;Validar^set;Responder^respond||Integracion de sistemas legacy,ETL de formatos,Migracion de datos|Detecta formato de entrada,Convierte a formato solicitado,Valida estructura|api,conversion,formatos,json,xml",
"02-Webhooks-API|API · Webhook Logger|API-Webhook-Logger|Registra todos los webhooks entrantes con timestamp headers body e IP para auditoria.|Webhook^webhook;Sellar^set;Guardar Log^sheets;Estadisticas^code;Confirmar^respond|googleSheetsOAuth2|Auditoria de webhooks,Debug de integraciones,Compliance y trazabilidad|Registra headers y body,Calcula estadisticas,Retencion configurable|api,webhook,logger,auditoria,log",
"02-Webhooks-API|API · Polling Inteligente|API-Polling-Inteligente|Hace polling a una API solo cuando hay cambios optimizando llamadas.|Cada min^schedule;Estado Anterior^sheetsRead;Consultar API^http;Cambio?^if;Procesar^set;Ignorar^set|googleSheetsOAuth2|Monitoreo eficiente,Deteccion de cambios,Sync incremental|Compara hash del estado anterior,Solo procesa si hay cambios,Reduce llamadas API|api,polling,eficiencia,cambios,http",
// 03-Email-Comunicacion
"03-Email-Comunicacion|Email · Programador de Envios|Email-Programador|Programa envios de email para fechas y horas especificas con plantillas dinamicas.|Schedule^schedule;Leer Cola^sheetsRead;Es Hora?^if;Renderar^code;Enviar^email;Marcar Enviado^sheets|googleSheetsOAuth2|Campanas programadas,Recordatorios automaticos,Comunicaciones escalonadas|Cola de emails en Sheets,Rendera variables dinamicas,Marca como enviado|email,programacion,campana,smtp,schedule",
"03-Email-Comunicacion|Email · Campana Drip|Email-Campana-Drip|Secuencia de emails escalonados que se envian segun el comportamiento del usuario.|Nuevo Lead^formTrg;Bienvenida^email;Esperar 3 dias^wait;Tips^email;Esperar 7 dias^wait;Oferta^email;Finalizar^sheets|googleSheetsOAuth2|Nurturing de leads,Onboarding de clientes,Cursos por email|Secuencia de N emails con waits,Personaliza cada email,Detiene si el usuario convierte|email,drip,nurturing,campana,secuencia",
"03-Email-Comunicacion|Email · Procesador de Adjuntos|Email-Procesador-Adjuntos|Detecta emails con adjuntos, los guarda en Drive y extrae metadatos.|Email^gmailTrg;Tiene Adjunto?^if;Guardar Drive^drive;Metadatos^code;Indexar^sheets;Notificar^slack|gmailOAuth2,googleDriveOAuth2,slackApi|Gestion documental,Facturas automaticas,Archivo de comprobantes|Filtra solo emails con adjuntos,Guarda en carpeta organizada,Extrae tipo y tamano|email,adjuntos,drive,archivos,gmail",
"03-Email-Comunicacion|Email · Digest Semanal|Email-Digest-Semanal|Recopila eventos de la semana y envia un resumen consolidado cada lunes.|Lunes 9am^calTrg;Recopilar^sheetsRead;Formatear^code;Enviar Digest^email|googleSheetsOAuth2|Boletines automaticos,Resumen de actividad,Reportes periodicos|Agrega eventos de la semana,Formatea como HTML,Personaliza por destinatario|email,digest,semanal,resumen,newsletter",
"03-Email-Comunicacion|Email · Respuesta Inteligente|Email-Respuesta-Inteligente|Genera respuestas sugeridas para emails recibidos usando IA.|Email^gmailTrg;Analizar IA^ai;Borrador^code;Guardar^sheets;Notificar^slack|gmailOAuth2,openAiApi,slackApi|Asistente de bandeja,Respuestas rapidas,Atencion al cliente|La IA propone respuestas posibles,Guarda borradores para revision,Aprende del tono de respuestas|email,ia,respuesta,gmail,openai",
"03-Email-Comunicacion|Email · Reenvio Condicional|Email-Reenvio-Condicional|Reenvia emails a diferentes personas segun reglas de remitente asunto o palabras.|Email^gmailTrg;Reglas^if;A Ventas^email;A Soporte^email;A Gerencia^email;Archivo^set|gmailOAuth2|Distribucion de bandeja,Enrutamiento de consultas,Buzon compartido|Multiples condiciones en cascada,Cada regla reenvia a un destinatario,Mantiene log de reenvios|email,reenvio,reglas,distribucion,gmail",
"03-Email-Comunicacion|Email · Newsletter desde RSS|Email-Newsletter-RSS|Compila articulos de feeds RSS y envia un newsletter HTML automaticamente.|Cada semana^schedule;Leer RSS^rss;Filtrar Top^code;Renderar HTML^code;Enviar^email||Curacion de contenido,Newsletter automatizado,Boletin de noticias|Filtra mejores articulos,Genera HTML con imagenes,Programa envio semanal|email,newsletter,rss,contenido,curacion",
"03-Email-Comunicacion|Email · Gestion de Rebotes|Email-Gestion-Rebotes|Detecta emails rebotados, marca contactos invalidos y limpia la lista.|Rebote^gmailTrg;Analizar^code;Es Bounce?^if;Marcar Invalido^sheets;Notificar^telegram;Limpiar Lista^set|gmailOAuth2,telegramApi|Limpieza de listas,Higiene de email marketing,Reduccion de spam|Detecta hard vs soft bounces,Marca contactos como invalidos,Reduce tasa de rebote|email,rebotes,limpieza,marketing,lista",
"03-Email-Comunicacion|Email · Inbox Distributor|Email-Inbox-Distributor|Distribuye emails de un buzon compartido entre miembros del equipo round-robin.|Email Compartido^gmailTrg;Proximo Agente^code;Asignar^sheets;Notificar^slack;Etiquetar^set|gmailOAuth2,slackApi|Soporte compartido,Rotacion de tareas,Gestion de ventas|Round-robin entre agentes,Balancea carga de trabajo,Notifica al agente asignado|email,distribucion,round-robin,soporte,equipo",
"03-Email-Comunicacion|Email · Cadena de Confirmacion|Email-Cadena-Confirmacion|Envia emails de confirmacion y hace follow-up si no se confirma en plazo.|Registro^formTrg;Enviar Confirmacion^email;Esperar 24h^wait;Confirmo?^if;Recordar^email;Esperar 48h^wait;Confirmo?^if;Urgente^telegram|googleSheetsOAuth2,telegramApi|Confirmacion de citas,Verificacion de registro,Onboarding de usuarios|Secuencia confirmacion recordatorio urgente,Cancela si confirma,Escala a humano tras agotar intentos|email,confirmacion,follow-up,secuencia,recordatorio",
"03-Email-Comunicacion|Comunicacion · SMS Masivos|Comunicacion-SMS-Masivos|Envia SMS masivos personalizados a una lista de contactos via API.|Lista^sheetsRead;Personalizar^code;Enviar SMS^http;Reporte^set|googleSheetsOAuth2|Alertas masivas,Marketing SMS,Notificaciones criticas|Personaliza con nombre y variables,Usa Twilio Vonage u otra API,Respeta normativas opt-in|sms,masivos,twilio,marketing,alertas",
"03-Email-Comunicacion|Email · Auto-Responder IA|Email-Auto-Responder-IA|Responde emails automaticamente con IA clasificando el tipo de consulta primero.|Email^gmailTrg;Clasificar IA^ai;Tipo?^if;Respuesta IA^ai;Enviar^email;Escalar Humano^slack|gmailOAuth2,openAiApi,slackApi|Soporte 24/7,FAQ automatizado,Filtro de consultas|Clasifica antes de responder,Solo auto-responde a tipos conocidos,Escala a humano si es complejo|email,auto-respuesta,ia,soporte,openai",
"03-Email-Comunicacion|Comunicacion · Notificaciones Push|Comunicacion-Push|Envia notificaciones push a moviles via OneSignal Firebase desde eventos.|Evento^webhook;Personalizar^code;Enviar Push^http;Log^sheets|googleSheetsOAuth2|App notifications,Alertas criticas,Engagement movil|Usa OneSignal o FCM,Segmenta por tags,Soporta titulo mas cuerpo|push,notificaciones,onesignal,firebase,movil",
"03-Email-Comunicacion|Email · Tracker de Lectura|Email-Tracker-Lectura|Rastrea que emails fueron abiertos usando pixel de tracking y registra estadisticas.|Email Enviado^set;Pixel Tracking^http;Apertura^webhook;Registrar^sheets;Estadisticas^code;Dashboard^sheets|googleSheetsOAuth2|Email marketing analytics,Seguimiento de campanas,Optimizacion de envios|Usa pixel invisible 1x1,Registra fecha e IP de apertura,Calcula tasa de apertura|email,tracking,apertura,analytics,marketing",
// 04-Datos-Scraping
"04-Datos-Scraping|Datos · Sync Web a BD|Datos-Web-a-BD|Extrae datos de una web periodicamente y los sincroniza con una base de datos.|Schedule^schedule;Scrapear^http;Parsear HTML^code;Diferencias?^code;Actualizar BD^postgres;Notificar^slack|postgres,slackApi|Sync de catalogos,Replicacion de datos,ETL automatizado|Detecta que cambio desde la ultima sync,Upsert inserta nuevos actualiza existentes,Mantiene log de cambios|datos,scraping,sync,postgres,etl",
"04-Datos-Scraping|Datos · Comparador de Precios|Datos-Comparador-Precios|Recopila precios de multiples tiendas y genera un comparativo con alertas de ofertas.|Schedule^schedule;Tienda A^http;Tienda B^http;Tienda C^http;Comparar^code;Mejor Precio^sheets;Alerta Oferta^telegram|googleSheetsOAuth2,telegramApi|Comparacion de precios,Caza-ofertas,Analisis competitivo|Scrapea 3 tiendas en paralelo,Calcula diferencia porcentual,Alerta si hay descuento|datos,precios,comparador,ofertas,scraping",
"04-Datos-Scraping|Datos · Stocks Bursatiles|Datos-Stocks-Bursatiles|Recopila cotizaciones bursatiles, calcula indicadores y alerta movimientos significativos.|Cada 15min^schedule;API Financiera^http;Calcular RSI^code;Umbral?^if;Alertar^telegram;Guardar Historico^sheets|googleSheetsOAuth2,telegramApi|Trading basico,Dashboard de inversiones,Alertas de mercado|Usa Alpha Vantage o Yahoo Finance,Calcula RSI y medias moviles,Alerta si cambia 5 por ciento|datos,stocks,finanzas,bursatil,trading",
"04-Datos-Scraping|Datos · Clima y Alertas|Datos-Clima-Alertas|Consulta APIs meteorologicas y alerta sobre condiciones extremas para operaciones.|Cada hora^schedule;API Clima^http;Alerta Extrema?^if;Notificar^telegram;Registrar^sheets|telegramApi,googleSheetsOAuth2|Alertas para operaciones,Planificacion logistica,Seguridad industrial|Usa OpenWeatherMap o WeatherAPI,Alerta lluvia viento temperatura,Relevante para cielo abierto|datos,clima,alertas,meteo,industrial",
"04-Datos-Scraping|Datos · Scraper de Redes Sociales|Datos-Scraper-Social|Extrae metricas de redes sociales likes comentarios shares periodicamente.|Diario^schedule;Instagram^http;Twitter X^http;YouTube^http;Consolidar^code;Dashboard^sheets|googleSheetsOAuth2|Analisis de engagement,Monitoreo de marca,Reportes de redes|Usa APIs oficiales o scraping,Normaliza metricas entre plataformas,Historico de tendencias|datos,redes-sociales,metricas,engagement,scraping",
"04-Datos-Scraping|Datos · Monitor de Competencia|Datos-Monitor-Competencia|Vigila webs de competidores: precios productos nuevos cambios de diseno.|Diario^schedule;Sitio Competidor^http;Detectar Cambios^code;Hay Novedad?^if;Alertar^telegram;Registrar^sheets|telegramApi,googleSheetsOAuth2|Inteligencia competitiva,Vigilancia de mercado,Price monitoring|Compara hash del HTML vs ayer,Detecta productos nuevos,Historico de tendencias|datos,competencia,monitoreo,precios,scraping",
"04-Datos-Scraping|Datos · Scraper de Empleos|Datos-Scraper-Empleos|Extrae ofertas de trabajo de portales de empleo y filtra por criterios.|Cada 6h^schedule;Portal Empleo^http;Filtrar^code;Coincide?^if;Guardar^sheets;Notificar^email|googleSheetsOAuth2|Busqueda de empleo automatizada,Analisis del mercado laboral,Reclutamiento pasivo|Filtra por palabras clave ubicacion salario,Deduplica ofertas vistas,Envia email con nuevas|datos,empleos,scraping,reclutamiento,filtro",
"04-Datos-Scraping|Datos · Tracker Inmobiliario|Datos-Tracker-Inmobiliario|Monitorea portales inmobiliarios y alerta nuevas propiedades que coinciden con criterios.|Cada 3h^schedule;Portal^http;Filtrar Criterios^code;Nueva?^if;Guardar^sheets;Alertar^telegram|telegramApi,googleSheetsOAuth2|Busqueda de propiedades,Analisis inmobiliario,Caza oportunidades|Filtra por precio zona habitaciones,Deduplica por ID,Alerta inmediata para hot|datos,inmobiliario,propiedades,alertas,scraping",
"04-Datos-Scraping|Datos · Agregador de Resenas|Datos-Agregador-Resenas|Recopila resenas de Google Yelp TripAdvisor y consolida en un dashboard.|Diario^schedule;Google Reviews^http;Yelp^http;TripAdvisor^http;Consolidar^code;Dashboard^sheets;Sentimiento IA^ai|googleSheetsOAuth2,openAiApi|Reputacion online,Analisis de satisfaccion,Benchmark competitivo|Normaliza formato entre plataformas,Calcula rating promedio ponderado,La IA clasifica sentimiento|datos,resenas,reputacion,reviews,scraping",
"04-Datos-Scraping|Datos · Agregador de Noticias|Datos-Agregador-Noticias|Compila noticias de multiples fuentes RSS y las filtra por relevancia.|Cada 2h^schedule;RSS 1^rss;RSS 2^rss;RSS 3^rss;Deduplicar^code;Filtrar IA^ai;Dashboard^sheets;Breaking^telegram|telegramApi,openAiApi,googleSheetsOAuth2|Media monitoring,Curacion de noticias,Inteligencia de mercado|Deduplica por titulo URL,La IA prioriza por relevancia,Alerta solo breaking|datos,noticias,rss,agregador,media",
"04-Datos-Scraping|Datos · Excel a JSON|Datos-Excel-a-JSON|Lee archivos Excel CSV, los normaliza y los convierte a JSON estructurado.|Archivo^formTrg;Leer CSV^code;Parsear^code;Normalizar^set;Guardar JSON^sheets;Responder^respond|googleSheetsOAuth2|Migracion de datos,Importacion de catalogos,ETL ligero|Detecta delimitador automatico,Mapea columnas a JSON,Valida tipos de datos|datos,excel,csv,json,conversion",
"04-Datos-Scraping|Datos · Deduplicacion|Datos-Deduplicacion|Detecta y elimina registros duplicados en bases de datos usando fuzzy matching.|Leer Datos^sheetsRead;Calcular Hash^code;Duplicados?^code;Marcar^sheets;Fusionar^code;Limpiar^set|googleSheetsOAuth2|Limpieza de CRM,Calidad de datos,Consolidacion de bases|Calcula hash de campos clave,Fuzzy matching para variaciones,Reporta que se fusiono|datos,deduplicacion,limpieza,calidad,crm",
"04-Datos-Scraping|Datos · Validacion de Datos|Datos-Validacion|Valida la integridad de datasets: emails validos telefonos formatos rangos.|Datos^sheetsRead;Validar^code;Es Valid?^if;Marcar OK^sheets;Corregir IA^ai;Reporte Errores^email|googleSheetsOAuth2,openAiApi|Calidad de datos,Limpieza de CRM,Validacion de formularios|Valida email telefono fecha,La IA corrige datos ambiguos,Reporta tasa de validez|datos,validacion,calidad,limpieza,crm",
"04-Datos-Scraping|Datos · Sync entre BDs|Datos-Sync-BDs|Sincroniza datos entre dos bases de datos diferentes manteniendo integridad.|Schedule^schedule;Leer Origen^postgres;Transformar^code;Upsert Destino^mysql;Verificar^code;Log^sheets|postgres,mysql|Replicacion de datos,Sync entre sistemas,Backup incremental|Lee cambios desde origen,Transforma al esquema destino,Upsert no duplica|datos,sync,postgres,mysql,replicacion",
"04-Datos-Scraping|Datos · Pipeline ETL|Datos-Pipeline-ETL|Pipeline ETL completo: extrae transforma y carga datos entre sistemas.|Schedule^schedule;Extraer^http;Limpiar^code;Transformar^code;Validar^if;Cargar^postgres;Reporte^email|postgres|Data warehouse,Integracion de sistemas,Reporting automatizado|Extract lee de API BD CSV,Transform limpia normaliza,Load escribe en destino|datos,etl,pipeline,data-warehouse,integracion",
// 05-Productividad
"05-Productividad|Productividad · Aprobacion Documentos|Prod-Aprobacion-Documentos|Flujo de aprobacion: envia documento espera revision y notifica resultado.|Solicitud^formTrg;Enviar Revisor^email;Esperar Respuesta^wait;Aprobado?^if;Notificar Solicitante^email;Registrar^sheets;Rechazar^slack|googleSheetsOAuth2,slackApi|Aprobacion de gastos,Revision de contratos,Workflow de compras|El revisor responde aprobar rechazar,Notifica al solicitante,Registra para auditoria|productividad,aprobacion,workflow,documentos,flujo",
"05-Productividad|Productividad · Control de Tiempo|Prod-Control-Tiempo|Registra horas trabajadas por proyecto y genera reportes de productividad.|Check-in^formTrg;Calcular Horas^code;Asignar Proyecto^code;Guardar^sheets;Reporte Semanal^email|googleSheetsOAuth2|Timesheet automatizado,Facturacion por horas,Productividad por proyecto|Calcula horas entre check-in check-out,Atribuye horas a proyectos,Genera reporte semanal|productividad,tiempo,horas,timesheet,reporte",
"05-Productividad|Productividad · Reporte de Gastos|Prod-Reporte-Gastos|Procesa recibos de gastos los categoriza y genera reportes de viaticos.|Recibo^formTrg;Extraer IA^ai;Categorizar^code;Aprobar?^if;Reembolsar^sheets;Notificar^email;Rechazar^slack|openAiApi,googleSheetsOAuth2,slackApi|Gastos corporativos,Viaticos,Rendicion de cuentas|La IA extrae importe fecha concepto,Categoriza automaticamente,Flujo de aprobacion|productividad,gastos,viaticos,reembolso,ia",
"05-Productividad|Productividad · Estado de Proyectos|Prod-Estado-Proyectos|Recopila estado de proyectos desde multiples fuentes y genera dashboard semanal.|Lunes 9am^calTrg;Leer Tareas^sheetsRead;Calcular Avance^code;Dashboard^sheets;Enviar^email;Slack^slack|googleSheetsOAuth2,slackApi|Reporting de proyectos,PMO automatizada,Visibilidad de avance|Calcula porcentaje completado retrasos riesgos,Dashboard en Sheets,Distribuye a stakeholders|productividad,proyectos,pmo,dashboard,reporte",
"05-Productividad|Productividad · Organizador Archivos|Prod-Organizador-Archivos|Organiza archivos automaticamente por tipo fecha o proyecto usando reglas.|Archivo Nuevo^webhook;Detectar Tipo^code;Mover Carpeta^drive;Indexar^sheets;Notificar^telegram|googleDriveOAuth2,telegramApi|Gestion documental,Limpieza de Drive,Archivo automatico|Reglas por extension nombre fecha,Mueve a carpeta correcta,Mantiene indice buscable|productividad,archivos,organizador,drive,automation",
"05-Productividad|Productividad · Sistema Recordatorios|Prod-Sistema-Recordatorios|Programa recordatorios recurrentes personalizables que llegan por multiples canales.|Schedule^schedule;Leer Recordatorios^sheetsRead;Es Hora?^if;Enviar Telegram^telegram;Enviar Email^email;Registrar^set|googleSheetsOAuth2,telegramApi|Recordatorios de tareas,Alertas periodicas,Gestion del tiempo|Define recordatorios en Sheets,Soporta recurrencia,Multi-canal|productividad,recordatorios,alertas,schedule,tareas",
"05-Productividad|Productividad · Sync Calendarios|Prod-Sync-Calendarios|Sincroniza eventos entre Google Calendar y otros sistemas Sheets Notion etc.|Evento^calTrg;Filtrar^code;Crear Sheets^sheets;Crear Notion^notion;Confirmar^set|googleSheetsOAuth2,notionApi|Sync multi-plataforma,Backup de calendarios,Coordinacion de equipos|Detecta nuevos eventos,Replica en Sheets y Notion,Evit a duplicados|productividad,calendar,sync,notion,coord",
"05-Productividad|Productividad · Bot Standup|Prod-Bot-Standup|Automatiza el standup diario: pregunta a cada miembro y compila respuestas.|Cada manana^calTrg;Preguntar^telegram;Compilar^code;Enviar Canal^slack;Guardar^sheets|telegramApi,slackApi|Daily standup remoto,Equipos distribuidos,Asincronia|Pregunta que hiciste que haras bloqueos,Compila en mensaje legible,Guarda historico|productividad,standup,scrum,agile,bot",
"05-Productividad|Productividad · Reporte Semanal IA|Prod-Reporte-Semanal-IA|La IA compila actividades de la semana y redacta un reporte ejecutivo.|Viernes 5pm^calTrg;Recopilar^sheetsRead;Redactar IA^ai;Enviar^email;Guardar^sheets|googleSheetsOAuth2,openAiApi|Reportes automaticos,Productividad personal,Gestion de equipos|Agrega tareas completadas y pendientes,La IA redacta narrativa ejecutiva,Personaliza el tono|productividad,reporte,ia,semanal,openai",
"05-Productividad|Productividad · Sync Sprint Board|Prod-Sync-Sprint-Board|Sincroniza tareas entre Trello Jira y Notion manteniendo estados consistentes.|Cambio^webhook;Detectar Cambio^code;Actualizar Notion^notion;Actualizar Trello^http;Confirmar^set|notionApi|Coordinacion de equipos,Single source of truth,Agile tooling|Detecta cambios de estado,Replica bidireccional,Evit a bucles infinitos|productividad,sprint,trello,notion,agile",
"05-Productividad|Productividad · Gestor Reuniones|Prod-Gestor-Reuniones|Programa reuniones envia invitaciones recordatorios y genera minutas.|Solicitud^formTrg;Verificar Disponibilidad^code;Crear Evento^http;Enviar Invitacion^email;Recordar 1h^wait;Minuta IA^ai;Enviar Minuta^email|openAiApi|Programacion automatizada,Gestion de calendario,Minutas automaticas|Verifica conflictos de horario,Recordatorio automatico,La IA genera minuta|productividad,reuniones,calendar,minuta,ia",
"05-Productividad|Productividad · Tracker Habitos|Prod-Tracker-Habitos|Registra habitos diarios calcula rachas y envia motivacion.|Registro^formTrg;Calcular Racha^code;Guardar^sheets;Racha Rota?^if;Motivacion IA^ai;Enviar^telegram|googleSheetsOAuth2,openAiApi,telegramApi|Desarrollo personal,Gamificacion,Bienestar|Calcula racha de dias consecutivos,La IA genera mensaje motivacional,Estadisticas visuales|productividad,habitos,racha,bienestar,gamificacion",
"05-Productividad|Productividad · Extractor Acciones|Prod-Extractor-Acciones|Analiza texto notas emails reuniones y extrae action items con responsable.|Texto^webhook;Extraer IA^ai;Crear Tareas^sheets;Asignar^slack;Confirmar^set|openAiApi,googleSheetsOAuth2,slackApi|Gestion de accion,Seguimiento de reuniones,Productividad personal|La IA identifica verbos de accion,Crea tareas automaticamente,Notifica a cada responsable|productividad,acciones,tareas,ia,openai",
"05-Productividad|Productividad · Onboarding Empleado|Prod-Onboarding-Empleado|Automatiza el onboarding: crea cuentas envia materiales y programa capacitacion.|Nuevo Empleado^formTrg;Crear Cuentas^http;Enviar Manual^email;Programar Capacitacion^calTrg;Notificar Equipo^slack;Checklist^sheets|slackApi,googleSheetsOAuth2|RRHH automatizado,Integracion de personal,Primer dia perfecto|Crea cuentas en sistemas,Envia manual y politicas,Programa sesiones de bienvenida|productividad,onboarding,rrhh,empleado,automatizacion",
"05-Productividad|Productividad · Backup Automatico|Prod-Backup-Automatico|Respalda automaticamente archivos y datos criticos a almacenamiento seguro.|Diario 2am^calTrg;Leer Datos^sheetsRead;Comprimir^code;Subir Backup^drive;Verificar^http;Notificar^telegram;Limpiar Antiguos^code|googleDriveOAuth2,telegramApi|Backup de datos,Continuidad de negocio,Compliance|Comprime antes de subir,Verifica integridad,Rota backups antiguos|productividad,backup,seguridad,drive,automatizacion",
// 06-Redes-Sociales
"06-Redes-Sociales|Redes · Multi-Plataforma|Redes-Multi-Plataforma|Publica el mismo contenido en multiples redes sociales con un solo flujo.|Contenido^webhook;Adaptar Formato^code;LinkedIn^http;Twitter X^http;Facebook^http;Telegram^telegram;Reporte^sheets|telegramApi,googleSheetsOAuth2|Gestion de redes,Calendario editorial,Cross-posting|Adapta formato por plataforma,Programa horarios optimos,Mantiene log de publicaciones|redes,multi-plataforma,publicar,cross-posting,contenido",
"06-Redes-Sociales|Redes · Social Listening|Redes-Social-Listening|Monitorea menciones de tu marca en redes sociales y analiza sentimiento.|Cada 2h^schedule;Buscar Menciones^http;Analizar IA^ai;Sentimiento^code;Negativo?^if;Alertar^telegram;Dashboard^sheets|openAiApi,telegramApi,googleSheetsOAuth2|Reputacion online,Gestion de crisis,Inteligencia de marca|Busca menciones en Twitter Reddit foros,La IA clasifica sentimiento,Alerta inmediata si negativo|redes,listening,sentimiento,marca,monitoreo",
"06-Redes-Sociales|Redes · Investigador Hashtags|Redes-Investigador-Hashtags|Analiza hashtags populares por nicho y sugiere los mejores para cada publicacion.|Nicho^webhook;Analizar Tendencias^http;Sugerir IA^ai;Ranking^sheets;Recomendar^telegram|openAiApi,googleSheetsOAuth2,telegramApi|Optimizacion de alcance,Estrategia de contenido,Analisis de tendencias|Analiza volumen y competencia,La IA sugiere combinacion optima,Mide evolucion temporal|redes,hashtags,tendencias,estrategia,ia",
"06-Redes-Sociales|Redes · Tracker Engagement|Redes-Tracker-Engagement|Recopila metricas de engagement de tus publicaciones y genera reportes.|Diario^schedule;Leer Metricas^http;Calcular KPIs^code;Dashboard^sheets;Insights IA^ai;Enviar^email|googleSheetsOAuth2,openAiApi|Analisis de rendimiento,Optimizacion de contenido,Reportes de redes|KPIs engagement rate alcance CTR,La IA sugiere mejor contenido,Compara performance entre publicaciones|redes,engagement,metricas,kpi,analytics",
"06-Redes-Sociales|Redes · Auto-Respuesta DM|Redes-Auto-Respuesta-DM|Responde automaticamente mensajes directos frecuentes con IA.|DM Recibido^webhook;Clasificar IA^ai;Tipo Conocido?^if;Respuesta Auto^http;Escalar Humano^telegram;Guardar^sheets|openAiApi,telegramApi|Atencion en redes,FAQ automatizado,Community management|La IA clasifica la intencion,Responde a FAQs automaticamente,Escala a humano si complejo|redes,dm,auto-respuesta,ia,comunidad",
"06-Redes-Sociales|Redes · Repurpose Contenido|Redes-Repurpose-Contenido|Transforma un contenido largo blog video en multiples formatos para redes.|Contenido Original^webhook;Extraer Ideas IA^ai;Generar Hilos^code;Generar Posts^code;Programar^sheets;Publicar^telegram|openAiApi,googleSheetsOAuth2|Content marketing,Calendario editorial,Maximizar ROI de contenido|Un blog post a N publicaciones,Adapta tono por plataforma,Programa escalonada|redes,repurpose,contenido,marketing,ia",
"06-Redes-Sociales|Redes · Builder UTM|Redes-Builder-UTM|Genera enlaces UTM trackeables automaticamente para campanas de redes.|Parametros^formTrg;Generar UTM^code;Acortar URL^http;Guardar^sheets;QR Code^code;Responder^respond|googleSheetsOAuth2|Tracking de campanas,Attribution de marketing,Analisis de trafico|Genera URL con source medium campaign,Opcionalmente acorta,Genera QR para offline|redes,utm,tracking,campana,marketing",
"06-Redes-Sociales|Redes · Analytics Dashboard|Redes-Analytics-Dashboard|Consolida metricas de todas tus redes en un dashboard unificado.|Semanal^schedule;Instagram^http;Facebook^http;YouTube^http;Consolidar^code;Dashboard^sheets;Insights^email|googleSheetsOAuth2|Reporting de redes,Vision 360 social,Benchmarking|Normaliza metricas entre plataformas,Calcula crecimiento semanal,Detecta tendencias|redes,analytics,dashboard,metricas,reporte",
"06-Redes-Sociales|Redes · Auditoria Perfil|Redes-Auditoria-Perfil|Analiza un perfil de redes sociales y genera un reporte de optimizacion.|Perfil^webhook;Scrapear^http;Analizar IA^ai;Recomendaciones^code;Reporte^email;Guardar^sheets|openAiApi,googleSheetsOAuth2|Optimizacion de perfil,Consultoria social,Auditoria competitiva|Analiza bio frecuencia engagement hashtags,La IA sugiere mejoras,Compara con mejores practicas|redes,auditoria,perfil,optimizacion,ia",
"06-Redes-Sociales|Redes · Cross-Post Automatico|Redes-Cross-Post|Detecta nuevas publicaciones en una red y las replica en otras automaticamente.|Nueva Publicacion^webhook;Adaptar^code;Publicar^http;Log^sheets;Confirmar^set|googleSheetsOAuth2|Sindicacion de contenido,Ahorro de tiempo,Presencia multi-plataforma|Adapta formato por plataforma,Evit a duplicados,Programa con retraso natural|redes,cross-post,sindicacion,automatico,multi",
"06-Redes-Sociales|Redes · Calendario Contenido|Redes-Calendario-Contenido|Gestiona un calendario editorial que publica contenido programado automaticamente.|Diario^schedule;Leer Calendario^sheetsRead;Es Hora?^if;Publicar^http;Marcar^sheets;Reporte^telegram|googleSheetsOAuth2,telegramApi|Gestion editorial,Publicacion programada,Content marketing|Calendario en Sheets con fecha hora contenido,Publica automaticamente,Notifica tras publicar|redes,calendario,editorial,programacion,contenido",
"06-Redes-Sociales|Redes · Concurso Sorteo|Redes-Concurso-Sorteo|Gestiona concursos en redes: recopila participaciones valida y sortea.|Participacion^webhook;Validar^code;Cumple Reglas?^if;Guardar^sheets;Cierre Concurso^calTrg;Sortear^code;Anunciar Ganador^telegram|googleSheetsOAuth2,telegramApi|Marketing viral,Engagement de comunidad,Lead generation|Valida follow like share hashtag,Sorteo aleatorio,Anuncia ganador y contacta|redes,concurso,sorteo,marketing,engagement",
// 07-DevOps
"07-DevOps|DevOps · Notificacion Deploy|DevOps-Notificacion-Deploy|Notifica al equipo cada deploy con detalles servicio version autor y changelog.|Webhook CI CD^webhook;Formatear^code;Notificar Slack^slack;Registrar^sheets;Health Check^http;OK?^if;Confirmar^set|slackApi,googleSheetsOAuth2|CI CD notifications,Visibility de deploys,Gestion de releases|Recibe webhook de GitHub Actions,Incluye commit autor y changelog,Verifica health post-deploy|devops,deploy,ci-cd,notificacion,slack",
"07-DevOps|DevOps · Analizador Logs|DevOps-Analizador-Logs|Analiza logs en busca de patrones de error y genera alertas inteligentes.|Logs^webhook;Filtrar Errores^code;Analizar IA^ai;Critico?^if;Alertar^telegram;Dashboard^sheets|openAiApi,telegramApi,googleSheetsOAuth2|Observabilidad,Deteccion proactiva,Troubleshooting automatizado|Filtra ERROR WARN de logs,La IA clasifica severidad y causa,Patrones recurrentes agrupados|devops,logs,analizador,observabilidad,ia",
"07-DevOps|DevOps · Backup BD Programado|DevOps-Backup-BD|Realiza backups automaticos de base de datos y verifica integridad.|Diario 3am^calTrg;Backup Postgres^code;Comprimir^code;Subir^drive;Verificar^code;Notificar^telegram;Limpiar Antiguos^code|googleDriveOAuth2,telegramApi|Continuidad de negocio,Disaster recovery,Compliance|Ejecuta pg_dump y comprime,Sube a almacenamiento seguro,Rota backups por retencion|devops,backup,postgres,disaster-recovery,automatico",
"07-DevOps|DevOps · Release Notes|DevOps-Release-Notes|Genera release notes automaticamente desde commits con IA.|Tag Release^webhook;Leer Commits^http;Generar IA^ai;Formatear^code;Publicar GitHub^http;Notificar^slack|openAiApi,slackApi|Gestion de versiones,Comunicacion de releases,Changelog automatizado|Lee commits desde el ultimo tag,La IA agrupa por tipo feat fix,Publica en GitHub y Slack|devops,release-notes,changelog,github,ia",
"07-DevOps|DevOps · Reinicio Contenedor|DevOps-Reinicio-Contenedor|Reinicia automaticamente contenedores Docker cuando detecta problemas.|Alerta^webhook;Identificar Contenedor^code;Reiniciar^http;Health Check^http;Recupero?^if;OK^slack;Fallo^telegram|slackApi,telegramApi|Self-healing,Minimizar downtime,Operaciones autonomas|Usa Docker API o Portainer,Verifica health despues,Escal a humano si no recupera|devops,docker,contenedor,self-healing,automatico",
"07-DevOps|DevOps · Monitor DNS|DevOps-Monitor-DNS|Verifica registros DNS y alerta si cambian o si hay problemas de resolucion.|Cada 30min^schedule;Resolver DNS^code;Cambio?^if;Alertar^telegram;Verificar MX^code;Registrar^sheets;OK^set|telegramApi,googleSheetsOAuth2|Seguridad DNS,Deteccion de hijacking,Monitoreo de infraestructura|Compara registros con snapshot,Verifica A MX TXT CNAME,Relevante para secuestro de dominio|devops,dns,monitor,seguridad,infraestructura",
"07-DevOps|DevOps · Escaneo Seguridad|DevOps-Escaneo-Seguridad|Programa escaneos de vulnerabilidades y alerta sobre hallazgos criticos.|Semanal^schedule;Escanear^http;Parsear^code;Critico?^if;Alertar Urgente^telegram;Crear Issue^http;Reporte^email|telegramApi|DevSecOps,Gestion de vulnerabilidades,Compliance de seguridad|Usa Trivy Nuclei etc,Prioriza por CVSS score,Crea issues automaticamente|devops,seguridad,escaneo,vulnerabilidades,devsecops",
"07-DevOps|DevOps · Benchmark Performance|DevOps-Benchmark-Performance|Ejecuta benchmarks de rendimiento periodicamente y detecta degradacion.|Semanal^schedule;Ejecutar Benchmark^http;Comparar Baseline^code;Degradado?^if;Alertar^telegram;Actualizar Baseline^sheets;Reporte^email|telegramApi,googleSheetsOAuth2|Performance monitoring,Deteccion de regresion,Optimizacion continua|Compara con baseline anterior,Detecta degradacion mayor a 10 por ciento,Mantiene historico|devops,benchmark,performance,monitoring,regresion",
"07-DevOps|DevOps · Respondedor Incidentes|DevOps-Respondedor-Incidentes|Workflow automatico de respuesta a incidentes: detecta diagnostica y mitiga.|Alerta^webhook;Clasificar Severidad^code;Critico?^if;Diagnosticar IA^ai;Aplicar Mitigacion^http;Notificar On-Call^telegram;Postmortem^sheets;Cerrar^slack|openAiApi,telegramApi,slackApi|Incident response,Gestion de crisis,SRE automation|Clasifica por severidad SEV1-SEV4,La IA sugiere causa raiz,Genera postmortem|devops,incidente,sre,respuesta,ia",
"07-DevOps|DevOps · Generador Changelog|DevOps-Generador-Changelog|Genera changelog estructurado desde el historial de commits.|Release^webhook;Leer Commits^http;Clasificar IA^ai;Generar Markdown^code;Guardar^drive;Publicar^http|openAiApi,googleDriveOAuth2|Documentacion de versiones,Transparencia de cambios,Release management|La IA clasifica commits,Genera CHANGELOG formato Keep a Changelog,Actualiza archivo existente|devops,changelog,commits,versiones,ia",
"07-DevOps|DevOps · Inventario Infraestructura|DevOps-Inventario-Infraestructura|Mantiene un inventario actualizado de toda la infraestructura automaticamente.|Diario^schedule;Consultar Docker^http;Consultar Cloud^http;Consolidar^code;Inventario^sheets;Diff^code;Cambios?^if;Alertar^slack|googleSheetsOAuth2,slackApi|Gestion de infraestructura,Asset management,Cost optimization|Inventaria contenedores VMs servicios,Detecta recursos nuevos o desaparecidos,Util para auditoria|devops,inventario,infraestructura,assets,auditoria",
"07-DevOps|DevOps · Verificacion Backup|DevOps-Verificacion-Backup|Verifica que los backups existan sean recientes y restaurables.|Diario^calTrg;Listar Backups^http;Reciente?^code;Restaurar Test^code;OK?^if;Confirmar^slack;Alertar^telegram|slackApi,telegramApi|Disaster recovery,Compliance,Integridad de backups|Verifica que el backup sea menor a 24h,Intenta restaurar en test,Alerta si corrupto|devops,backup,verificacion,disaster-recovery,testing",
"07-DevOps|DevOps · Monitor Costos Cloud|DevOps-Monitor-Costos|Monitorea el gasto en la nube y alerta si supera el presupuesto.|Diario^schedule;Consultar API^http;Calcular Gasto^code;Sobre Presupuesto?^if;Alertar^telegram;Dashboard^sheets;Sugerencia IA^ai|telegramApi,openAiApi,googleSheetsOAuth2|FinOps,Optimizacion de costos,Control presupuestario|Consulta API de costos AWS Azure GCP,Proyecta gasto mensual,La IA sugiere donde ahorrar|devops,costos,cloud,finops,presupuesto",
"07-DevOps|DevOps · Auto-Escalado|DevOps-Auto-Escalado|Escala recursos automaticamente segun la carga del sistema.|Cada 5min^schedule;Leer Metricas^http;Alta Carga?^if;Escalar Up^http;Baja Carga?^if;Escalar Down^http;Registrar^sheets;Notificar^slack|slackApi,googleSheetsOAuth2|Auto-scaling,Optimizacion de recursos,Alta disponibilidad|Monitorea CPU RAM latencia,Escala cuando supera umbral,Reduce instancias cuando baja|devops,escalado,auto-scaling,cloud,recursos",
"07-DevOps|DevOps · Pipeline Calidad|DevOps-Pipeline-Calidad|Ejecuta quality gates: lint tests coverage antes de permitir merge.|PR Creado^webhook;Ejecutar Lint^http;Ejecutar Tests^http;Coverage OK?^if;Aprobar^http;Bloquear^http;Notificar^slack|slackApi|Code quality gates,CI CD automation,DevOps best practices|Ejecuta ESLint Prettier pytest,Bloquea merge si coverage bajo,Notifica resultado al autor|devops,calidad,ci-cd,lint,testing",
// 08-Marketing
"08-Marketing|Marketing · Scoring Leads Avanzado|Mkt-Scoring-Leads|Puntua leads con criterios demograficos mas comportamientoales y enruta a ventas.|Lead^webhook;Calcular Score^code;Enriquecer IA^ai;Score Alto?^if;Asignar Ventas^slack;Nurturing^email;Guardar^sheets|openAiApi,slackApi,googleSheetsOAuth2|Priorizacion de ventas,Lead routing,Marketing automation|Score basado en perfil mas comportamiento,La IA enriquece con datos,Solo pasa a ventas si score alto|marketing,leads,scoring,routing,crm",
"08-Marketing|Marketing · Segmentacion Audiencia|Mkt-Segmentacion|Segmenta contactos en listas basadas en comportamiento y atributos demograficos.|Contacto^webhook;Calcular Segmento^code;Actualizar Lista^sheets;Trigger Campana^email;Sync CRM^http;Confirmar^set|googleSheetsOAuth2|Email marketing,Personalizacion,Marketing automation|Segmenta por industria cargo comportamiento,Actualiza dinamicamente,Triggers por segmento|marketing,segmentacion,audiencia,crm,personalizacion",
"08-Marketing|Marketing · Performance Campanas|Mkt-Performance-Campanas|Recopila metricas de campanas multi-canal y calcula ROI y CAC.|Semanal^schedule;Leer Metricas^http;Calcular ROI^code;Dashboard^sheets;Insights IA^ai;Enviar^email|googleSheetsOAuth2,openAiApi|Marketing analytics,Optimizacion de presupuesto,Attribution|Consolida metricas de Google Ads Meta email,Calcula ROI CAC LTV,La IA sugiere reallocacion|marketing,performance,roi,cac,analytics",
"08-Marketing|Marketing · Social Proof|Mkt-Social-Proof|Recopila testimonios y resenas positivas para usar como social proof.|Resena Positiva^webhook;Extraer Testimonio^code;Aprobar?^if;Publicar Web^http;Compartir Redes^telegram;Guardar^sheets|telegramApi,googleSheetsOAuth2|Marketing de prueba social,Generacion de contenido,Conversion|Filtra solo 4-5 estrellas,La IA extrae frase impactante,Publica en web y redes|marketing,social-proof,testimonios,resenas,conversion",
"08-Marketing|Marketing · Programa Referidos|Mkt-Programa-Referidos|Gestiona referidos: tracking validacion y recompensas automaticas.|Nueva Referencia^webhook;Validar^code;Es Cliente Nuevo?^if;Aplicar Recompensa^code;Notificar Ambos^email;Actualizar^sheets;Reporte^telegram|googleSheetsOAuth2,telegramApi|Growth marketing,Customer advocacy,Lead generation|Valida que sea cliente nuevo,Aplica recompensa a ambos,Tracking de conversion|marketing,referidos,growth,recompensas,advocacy",
"08-Marketing|Marketing · Customer Journey|Mkt-Customer-Journey|Rastrea el journey del cliente touchpoint por touchpoint y genera mapa visual.|Evento^webhook;Identificar Touchpoint^code;Actualizar Journey^sheets;Calcular Etapa^code;Trigger Accion^email;Analisis IA^ai;Dashboard^sheets|googleSheetsOAuth2,openAiApi|Customer experience,Marketing attribution,Optimizacion de funnel|Registra cada interaccion,Calcula etapa del funnel,La IA detecta cuellos|marketing,customer-journey,funnel,touchpoints,experience",
"08-Marketing|Marketing · AB Testing|Mkt-AB-Testing|Ejecuta tests AB en campanas y declara ganador automaticamente con significancia.|Test Config^formTrg;Dividir Audiencia^code;Enviar Variante A^email;Enviar Variante B^email;Esperar Resultados^wait;Calcular Significancia^code;Ganador?^if;Declarar^sheets;Notificar^slack|googleSheetsOAuth2,slackApi|Optimizacion de campanas,Email testing,Data-driven marketing|Divide audiencia 50/50,Calcula significancia estadistica,Declara ganador y guarda|marketing,ab-testing,experimentos,optimizacion,data-driven",
"08-Marketing|Marketing · Calculadora ROI|Mkt-Calculadora-ROI|Calcula ROI de campanas en tiempo real y sugiere optimizaciones.|Diario^schedule;Leer Inversion^sheetsRead;Leer Conversion^http;Calcular ROI^code;ROI Bajo?^if;Alertar^telegram;Sugerencia IA^ai;Dashboard^sheets|googleSheetsOAuth2,openAiApi,telegramApi|Marketing analytics,Optimizacion presupuestaria,Decisiones data-driven|ROI ingresos menos inversion,Alerta si ROI menor a cero,La IA sugiere invertir mas o menos|marketing,roi,calculadora,analytics,optimizacion",
"08-Marketing|Marketing · Audience Builder|Mkt-Audience-Builder|Construye audiencias custom para ads a partir de datos de CRM.|Datos CRM^sheetsRead;Filtrar Criterios^code;Crear Audiencia^http;Sync Facebook^http;Sync Google^http;Confirmar^sheets;Reporte^email|googleSheetsOAuth2|Lookalike audiences,Custom audiences,Ad targeting|Filtra CRM por criterios,Crea audiencia en Facebook Google Ads,Sincroniza periodicamente|marketing,audiencia,ads,facebook,google",
"08-Marketing|Marketing · Calendario Editorial|Mkt-Calendario-Editorial|Gestiona y publica contenido segun un calendario editorial multi-canal.|Diario^schedule;Leer Calendario^sheetsRead;Hoy?^if;Preparar Contenido^code;Publicar Redes^http;Enviar Email^email;Marcar^sheets;Reporte^telegram|googleSheetsOAuth2,telegramApi|Content marketing,Gestion editorial,Publicacion programada|Calendario maestro en Sheets,Publica en el canal correcto,Notifica al equipo|marketing,calendario,editorial,contenido,programacion",
"08-Marketing|Marketing · Ranker Contenido|Mkt-Ranker-Contenido|Analiza performance de todo el contenido y ranking por engagement y conversion.|Semanal^schedule;Leer Metricas^http;Calcular Score^code;Ranking^sheets;Top 10?^if;Promover^email;Insights IA^ai;Notificar^slack|googleSheetsOAuth2,openAiApi,slackApi|Content optimization,Evergreen detection,ROI de contenido|Score por engagement mas conversion,Identifica evergreen,La IA sugiere republicar|marketing,contenido,ranking,engagement,analytics",
"08-Marketing|Marketing · Funnel Tracker|Mkt-Funnel-Tracker|Rastrea conversiones en cada etapa del funnel y detecta cuellos de botella.|Evento^webhook;Etapa Funnel^code;Actualizar^sheets;Calcular Tasas^code;Cuello Botella?^if;Alertar^telegram;Sugerencia IA^ai;Dashboard^sheets|googleSheetsOAuth2,openAiApi,telegramApi|Optimizacion de conversion,CRO,Analytics de funnel|Registra conversion en cada etapa,Calcula tasa etapa a etapa,La IA detecta donde se pierden|marketing,funnel,conversion,cro,analytics",
"08-Marketing|Marketing · Lead Nurture|Mkt-Lead-Nurture|Secuencia de emails educativos que nutre leads hasta que estan listos para comprar.|Nuevo Lead^formTrg;Email 1 Bienvenida^email;Esperar 2 dias^wait;Email 2 Educacion^email;Esperar 3 dias^wait;Email 3 Caso Exito^email;Esperar 2 dias^wait;Email 4 Oferta^email;Convertido?^if;Detener^set;Sales Handoff^slack|googleSheetsOAuth2,slackApi|Lead nurturing,Email marketing,Sales enablement|Secuencia de 4-5 emails con waits,Cada email educa y avanza,Detiene si convierte|marketing,nurture,secuencia,leads,email",
"08-Marketing|Marketing · Promocion Eventos|Mkt-Promocion-Eventos|Automatiza la promocion de eventos: recordatorios confirmaciones y follow-up.|Crear Evento^formTrg;Promocionar^email;Esperar 7 dias^wait;Recordar^email;Esperar 1 dia^wait;Ultima Llamada^telegram;Dia Evento^calTrg;Recordatorio Final^email;Post-Evento^calTrg;Follow-up^email;Encuesta^formTrg|googleSheetsOAuth2,telegramApi|Event marketing,Webinar promotion,Engagement de asistentes|Cronologia promocion recordatorios evento followup,Personaliza por asistente,Recopila feedback|marketing,eventos,webinar,promocion,follow-up",
"08-Marketing|Marketing · Reactivacion Clientes|Mkt-Reactivacion-Clientes|Identifica clientes inactivos y lanza campanas de reactivacion personalizadas.|Mensual^schedule;Identificar Inactivos^sheetsRead;Segmentar^code;Campana Gancho^email;Esperar 5 dias^wait;Respondio?^if;Oferta Especial^email;Registrar^sheets;Reporte^telegram|googleSheetsOAuth2,telegramApi|Win-back campaigns,Customer retention,Churn reduction|Identifica inactivos mayor a 90 dias,Primero gancho luego oferta especial,Mide tasa de reactivacion|marketing,reactivacion,win-back,retencion,churn",
// 09-Industrial-Plantas
"09-Industrial-Plantas|Industrial · Consumo Energetico|Ind-Consumo-Energetico|Monitorea el consumo electrico detecta picos anomalos y genera reportes de eficiencia.|Cada 15min^schedule;Leer Medidores^http;Calcular Demanda^code;Pico Anomalo?^if;Alertar^telegram;Guardar^sheets;Reporte Diario^email|telegramApi,googleSheetsOAuth2|Gestion energetica,Deteccion de fugas,Optimizacion de costos|Lee datos de medidores Modbus OPC,Detecta picos sobre percentil 95,Reporte de eficiencia diaria|industrial,energia,consumo,eficiencia,oilgas",
"09-Industrial-Plantas|Industrial · Tratamiento de Agua|Ind-Tratamiento-Agua|Monitorea parametros de calidad de agua pH turbidez cloro y alerta desviaciones.|Cada 30min^schedule;Leer Sensores^http;Evaluar Calidad^code;Dentro de Rango?^if;Alertar Calidad^telegram;Registrar^sheets;Reporte Turno^email|telegramApi,googleSheetsOAuth2|Plantas desaladoras,Tratamiento de efluentes,Cumplimiento ambiental|Monitorea pH turbidez cloro TDS,Cada parametro tiene rango seguro,Relevante para desaladoras|industrial,agua,desaladora,calidad,sensores",
"09-Industrial-Plantas|Industrial · Analisis Vibraciones|Ind-Analisis-Vibraciones|Analiza datos de vibracion de equipos rotativos para deteccion temprana de fallas.|Cada hora^schedule;Leer Acelerometros^http;Calcular FFT^code;Hay Armonico?^if;Alertar Mantto^telegram;Crear OT^sheets;Historico^sheets|telegramApi,googleSheetsOAuth2|Mantenimiento predictivo,Bombas y motores,Deteccion de fallas|Analiza espectro de frecuencias FFT,Detecta armonicos de falla,Genera OT predictivo|industrial,vibraciones,predictivo,mantenimiento,fft",
"09-Industrial-Plantas|Industrial · Mantenimiento Predictivo|Ind-Mantenimiento-Predictivo|Programa mantenimiento basado en condicion real del equipo no en tiempo fijo.|Diario^schedule;Leer Condicion^http;Calcular Degradacion^code;Umbral?^if;Programar Mantto^sheets;Generar OT^code;Notificar^telegram;Optimizar^code|telegramApi,googleSheetsOAuth2|Mantenimiento basado en condicion,Optimizacion de costos,Reduccion de paradas|Combina vibracion temperatura horas operacion,Predice vida util restante,Solo programa cuando necesario|industrial,predictivo,mantenimiento,condicion,oilgas",
"09-Industrial-Plantas|Industrial · Reporte de Seguridad|Ind-Reporte-Seguridad|Sistema de reportes de observaciones de seguridad con seguimiento de acciones correctivas.|Observacion^formTrg;Clasificar^code;Accion Inmediata?^if;Alertar HSE^telegram;Crear Accion^sheets;Asignar Responsable^slack;Esperar Cierre^wait;Cerrada?^if;Verificar^set;Reportar^email|telegramApi,slackApi,googleSheetsOAuth2|Cultura de seguridad,Gestion de hallazgos HSE,Cumplimiento de normativas|Observaciones preventivas mas condiciones inseguras,Genera accion correctiva con responsable,Hace seguimiento hasta cierre|industrial,seguridad,hse,observaciones,acciones",
"09-Industrial-Plantas|Industrial · Compliance Ambiental|Ind-Compliance-Ambiental|Monitorea emisiones y parametros ambientales para cumplimiento normativo.|Continuo^schedule;Leer Monitores^http;Dentro de Limite?^if;Alertar^telegram;Registrar^sheets;Reporte Mensual^email|telegramApi,googleSheetsOAuth2|Cumplimiento de normas,Reportes ambientales,Mineria y refinerias|Monitorea NOx SOx particulas ruido,Compara con limites legales,Genera reporte mensual|industrial,ambiental,compliance,emisiones,refineria",
"09-Industrial-Plantas|Industrial · Gestion Almacen|Ind-Gestion-Almacen|Gestiona stock de repuestos: niveles minimos reservas y solicitudes de compra.|Movimiento^webhook;Actualizar Stock^sheets;Bajo Minimo?^if;Generar OC^code;Aprobar^email;Notificar Compras^slack;Registrar^sheets|googleSheetsOAuth2,slackApi|Gestion de inventario,Reposicion automatica,Control de stock|Mantén stock minimo por repuesto,Genera OC cuando baja minimo,Flujo de aprobacion|industrial,almacen,stock,repuestos,compras",
"09-Industrial-Plantas|Industrial · Cadena de Suministro|Ind-Cadena-Suministro|Monitorea proveedores y alerta retrasos que puedan afectar la produccion.|Diario^schedule;Check Proveedores^http;Retraso?^if;Impacto?^code;Critico?^if;Alertar Produccion^telegram;Plan B^slack;Registrar^sheets|telegramApi,slackApi,googleSheetsOAuth2|Supply chain management,Continuidad de produccion,Gestion de proveedores|Verifica estado de pedidos,Evalua impacto en produccion,Sugiere proveedores alternativos|industrial,suministro,proveedores,logistica,oilgas",
"09-Industrial-Plantas|Industrial · Control de Calidad|Ind-Control-Calidad|Checkpoint de calidad: registra mediciones evalua conformidad y genera certificados.|Muestra^formTrg;Medir^code;Conforme?^if;Aprobar Lote^set;Certificado^email;Rechazar Lote^slack;Investigar^code;Registrar^sheets|googleSheetsOAuth2,slackApi|Aseguramiento de calidad,Control estadistico,Certificacion de lotes|Registra mediciones contra especificaciones,Aprueba o rechaza lote,Genera certificado|industrial,calidad,lote,control,certificacion",
"09-Industrial-Plantas|Industrial · Registro de Lotes|Ind-Registro-Lotes|Mantiene trazabilidad completa de lotes de produccion: inputs procesos outputs.|Lote^formTrg;Asociar Inputs^code;Registrar Proceso^set;Outputs^sheets;Trazabilidad^code;Certificado^email;Archivo^drive|googleSheetsOAuth2,googleDriveOAuth2|Trazabilidad de produccion,Compliance ISO,Recall management|Asocia materias primas con producto final,Registra cada etapa,Permite trazabilidad ante recall|industrial,lotes,trazabilidad,iso,produccion",
"09-Industrial-Plantas|Industrial · Analizador Paradas|Ind-Analizador-Paradas|Registra paradas de produccion calcula impacto y analiza causas raiz.|Parada^formTrg;Calcular Impacto^code;Registrar^sheets;Analizar Causa IA^ai;Recurrente?^code;Alertar^telegram;Reporte Semanal^email;Pareto^sheets|openAiApi,telegramApi,googleSheetsOAuth2|Analisis de downtime,Mejora continua,OEE|Calcula tiempo y costo de parada,La IA sugiere causa raiz,Genera diagrama de Pareto|industrial,paradas,downtime,oee,mejora",
"09-Industrial-Plantas|Industrial · Eficiencia Energetica|Ind-Eficiencia-Energetica|Calcula KPIs de eficiencia energetica y sugiere optimizaciones.|Diario^calTrg;Leer Consumo^http;Calcular KPIs^code;Comparar Benchmark^code;Ineficiente?^if;Sugerencia IA^ai;Reporte^email;Dashboard^sheets|openAiApi,googleSheetsOAuth2|Gestion energetica,Sostenibilidad,Reduccion de costos|KPI kWh por unidad producida,Compara contra benchmark historico,La IA sugiere reducir consumo|industrial,energia,eficiencia,kpis,sostenibilidad",
"09-Industrial-Plantas|Industrial · Inventario Quimicos|Ind-Inventario-Quimicos|Gestiona inventario de productos quimicos con hojas de seguridad y alertas de caducidad.|Movimiento^webhook;Actualizar^sheets;Caduca Pronto?^code;Bajo Minimo?^if;Reordenar^email;FDS^code;Registrar^sheets|googleSheetsOAuth2|Gestion de quimicos,Seguridad quimica,Compliance|Cada quimico tiene caducidad y FDS,Alerta antes de caducar,Mantiene hoja de seguridad accesible|industrial,quimicos,inventario,seguridad,fds",
"09-Industrial-Plantas|Industrial · Recordatorio Permisos|Ind-Recordatorio-Permisos|Recordatorio automatico de renovacion de permisos licencias y certificaciones.|Mensual^schedule;Leer Vencimientos^sheetsRead;Por Vencer?^code;Alertar Responsable^email;Urgente?^if;Escalar^telegram;Actualizar^sheets|googleSheetsOAuth2,telegramApi|Gestion de cumplimiento,Permisos operativos,Evitar multas|Base de datos de permisos con fechas,Alerta 30 15 7 dias antes,Escala a gerencia si urgente|industrial,permisos,cumplimiento,licencias,vencimientos",
"09-Industrial-Plantas|Industrial · Tracker Capacitaciones|Ind-Tracker-Capacitaciones|Gestiona capacitaciones obligatorias: programa registra y certifica cumplimiento.|Empleado^formTrg;Asignar Cursos^code;Notificar^email;Esperar^wait;Completo?^if;Registrar^sheets;Certificado^email;No Completo^telegram;Reporte Cumplimiento^email|googleSheetsOAuth2,telegramApi|Compliance de capacitacion,Seguridad laboral,Gestion de RRHH|Asigna cursos obligatorios por rol,Hace seguimiento de finalizacion,Genera certificados|industrial,capacitacion,cumplimiento,rrhh,seguridad",
"09-Industrial-Plantas|Industrial · Registro Peligros|Ind-Registro-Peligros|Identificacion y registro de peligros HIRA con evaluacion de riesgo y controles.|Peligro^formTrg;Evaluar Riesgo^code;Tolerable?^if;Implementar Control^slack;Registrar^sheets;Revisar Periodicamente^calTrg;Eficaz?^code;Reportar^email|googleSheetsOAuth2,slackApi|HSE profesional,Evaluacion de riesgos,Jerarquia de controles|Evaluacion segun matriz probabilidad consecuencia,Define controles siguiendo jerarquia,Revisa eficacia periodicamente|industrial,peligros,hira,riesgo,controles",
"09-Industrial-Plantas|Industrial · Respuesta Emergencia|Ind-Respuesta-Emergencia|Workflow de activacion de respuesta a emergencias: notifica moviliza y documenta.|Emergencia^webhook;Clasificar^code;Critica?^if;Activar Protocolo^telegram;Movilizar Brigada^slack;Notificar Gerencia^email;Registrar^sheets;Post-Evento^wait;Investigar^ai;Lecciones^sheets;Reporte^email|telegramApi,slackApi,openAiApi,googleSheetsOAuth2|Gestion de crisis,Respuesta a emergencias,Seguridad industrial|Clasifica emergencia por tipo y severidad,Moviliza brigada automaticamente,Post-evento investigacion y lecciones|industrial,emergencia,crisis,respuesta,seguridad",
"09-Industrial-Plantas|Industrial · Gestion Contratistas|Ind-Gestion-Contratistas|Gestiona contratistas: documentacion permisos induccion y control de acceso.|Contratista^formTrg;Verificar Docs^code;Documentacion OK?^if;Induccion Pendiente?^if;Asignar Induccion^email;Esperar^wait;Aprobo?^if;Generar Pase^code;Notificar Acceso^telegram;Registrar^sheets;Rechazar^slack|googleSheetsOAuth2,telegramApi,slackApi|Gestion de contratistas,Control de acceso,Compliance de seguridad|Verifica seguros RUT certificaciones,Induccion de seguridad obligatoria,Genera pase de acceso temporal|industrial,contratistas,acceso,induccion,compliance",
];

// ── Mapeo tipo → nodo n8n ──
const NODE_DEFS={
  schedule:{type:'n8n-nodes-base.scheduleTrigger',tv:1.2,params:{rule:{interval:[{field:'hours',hoursInterval:1}]}}},
  webhook:{type:'n8n-nodes-base.webhook',tv:2,params:{httpMethod:'POST',path:'endpoint',responseMode:'responseNode',options:{}}},
  manual:{type:'n8n-nodes-base.manualTrigger',tv:1,params:{}},
  rss:{type:'n8n-nodes-base.rssFeedReadTrigger',tv:1,params:{url:'https://feeds.example.com/feed',options:{}}},
  gmailTrg:{type:'n8n-nodes-base.gmailTrigger',tv:1.2,params:{pollTimes:{item:[{mode:'everyMinute'}]},options:{}}},
  tgTrg:{type:'n8n-nodes-base.telegramTrigger',tv:1.2,params:{updates:['message'],additionalFields:{}}},
  calTrg:{type:'n8n-nodes-base.scheduleTrigger',tv:1.2,params:{rule:{interval:[{field:'days',triggerAtHour:8}]}}},
  formTrg:{type:'n8n-nodes-base.webhook',tv:2,params:{httpMethod:'POST',path:'form',options:{}}},
  ai:{type:'n8n-nodes-base.httpRequest',tv:4.2,params:{method:'POST',url:'https://api.openai.com/v1/chat/completions',authentication:'predefinedCredentialType',nodeCredentialType:'openAiApi',sendBody:true,specifyBody:'json',jsonBody:'={"model":"gpt-4o-mini","messages":[{"role":"system","content":"Asistente experto"},{"role":"user","content":"Procesa la entrada"}]}',options:{}}},
  if:{type:'n8n-nodes-base.if',tv:2.2,params:{conditions:{options:{caseSensitive:false,leftValue:'',typeValidation:'loose'},conditions:[{id:'c1',leftValue:'={{ $json.valor }}',rightValue:'true',operator:{type:'string',operation:'equals'}}],combinator:'and'},options:{}}},
  code:{type:'n8n-nodes-base.code',tv:2,params:{jsCode:'const items = $input.all();\nreturn items.map(i => ({ json: { ...i.json, procesado: true, fecha: new Date().toISOString() } }));'}},
  set:{type:'n8n-nodes-base.set',tv:3.4,params:{assignments:{assignments:[{id:'a1',name:'resultado',value:'={{ $json }}',type:'string'}]},options:{}}},
  sheets:{type:'n8n-nodes-base.googleSheets',tv:4.5,params:{operation:'append',documentId:{__rl:true,mode:'id',value:'TU_SPREADSHEET_ID'},sheetName:{__rl:true,mode:'name',value:'Datos'},columns:{mappingMode:'autoMapInputData',value:{},matchingColumns:[]},options:{}}},
  sheetsRead:{type:'n8n-nodes-base.googleSheets',tv:4.5,params:{operation:'read',documentId:{__rl:true,mode:'id',value:'TU_SPREADSHEET_ID'},sheetName:{__rl:true,mode:'name',value:'Datos'},options:{}}},
  notion:{type:'n8n-nodes-base.notion',tv:2.2,params:{operation:'create',databaseId:{__rl:true,mode:'id',value:'TU_DATABASE_ID'},title:'={{ $json.titulo }}',options:{}}},
  postgres:{type:'n8n-nodes-base.postgres',tv:2.5,params:{operation:'executeQuery',query:'SELECT * FROM tabla LIMIT 10'}},
  mysql:{type:'n8n-nodes-base.mySql',tv:2.4,params:{operation:'executeQuery',query:'SELECT * FROM tabla LIMIT 10'}},
  http:{type:'n8n-nodes-base.httpRequest',tv:4.2,params:{url:'https://api.example.com/endpoint',options:{}}},
  drive:{type:'n8n-nodes-base.googleDrive',tv:3,params:{operation:'upload',name:'archivo.txt',folderId:{__rl:true,mode:'list',value:'My Drive'},inputDataFieldName:'data',options:{}}},
  telegram:{type:'n8n-nodes-base.telegram',tv:1.2,params:{chatId:'TU_CHAT_ID',text:'=Notificacion: {{ $json.mensaje || JSON.stringify($json) }}',additionalFields:{}}},
  email:{type:'n8n-nodes-base.emailSend',tv:2.1,params:{fromEmail:'noreply@tudominio.com',toEmail:'destino@email.com',subject:'Notificacion',emailFormat:'text',message:'={{ $json.mensaje || "Notificacion automatica" }}',options:{}}},
  slack:{type:'n8n-nodes-base.slack',tv:2.3,params:{select:'channel',channelId:{__rl:true,mode:'name',value:'general'},text:'=Notificacion: {{ $json.mensaje }}',otherOptions:{}}},
  discord:{type:'n8n-nodes-base.discord',tv:2,params:{authentication:'webhook',webhookUrl:'TU_DISCORD_WEBHOOK',content:'=Notificacion: {{ $json.mensaje }}',options:{}}},
  wait:{type:'n8n-nodes-base.wait',tv:1.1,params:{amount:1,unit:'days'}},
  respond:{type:'n8n-nodes-base.respondToWebhook',tv:1.1,params:{respondWith:'json',responseBody:'={{ JSON.stringify($json) }}',options:{}}},
};

function makeNode(name,typeKey,i){
  const d=NODE_DEFS[typeKey]||NODE_DEFS.http;
  return {parameters:JSON.parse(JSON.stringify(d.params)),id:'n-'+i+'-'+Math.random().toString(36).slice(2,8),name,type:d.type,typeVersion:d.tv,position:[i*260-260,0]};
}
function makeWorkflow(name,flowTypes,labels){
  const nodes=[]; const connections={};
  flowTypes.forEach((t,i)=>{
    const node=makeNode(labels[i]||('Nodo '+(i+1)),t,i);
    if(t==='webhook'||t==='formTrg') node.webhookId='wh-'+i;
    nodes.push(node);
    if(i<flowTypes.length-1) connections[node.name]={main:[[{node:labels[i+1]||('Nodo '+(i+2)),type:'main',index:0}]]};
  });
  return {name,nodes,connections,pinData:{},settings:{executionOrder:'v1'},active:false,tags:[]};
}

// ── Procesar ──
const TEMPLATES=RAW.map(T);
console.log(`Plantillas a generar: ${TEMPLATES.length}`);

let gen=0;
const dataEntries=[];
for(const tpl of TEMPLATES){
  const dir=path.join(base,tpl.cat);
  if(!fs.existsSync(dir)) fs.mkdirSync(dir,{recursive:true});
  const labels=tpl.flow.map(f=>f[0]);
  const types=tpl.flow.map(f=>f[1]);
  const wf=makeWorkflow(tpl.name,types,labels);
  fs.writeFileSync(path.join(dir,tpl.file+'.json'),JSON.stringify(wf,null,2),'utf8');
  gen++;
  dataEntries.push(tpl);
}

// Actualizar data.js
const dataJsPath=path.join(base,'data.js');
let dataJs=fs.readFileSync(dataJsPath,'utf8');
const entriesStr=dataEntries.map(e=>
  `  {cat:"${e.cat}",name:"${e.name}",file:"${e.file}",\n   desc:"${e.desc}",\n   flow:${JSON.stringify(e.flow)},creds:${JSON.stringify(e.creds)},\n   uses:${JSON.stringify(e.uses)},\n   obs:${JSON.stringify(e.obs)},\n   tags:${JSON.stringify(e.tags)}},`
).join('\n');
dataJs=dataJs.replace(/\n\];\s*$/,'\n  // ---- Plantillas generadas (gen-200.js) ----\n'+entriesStr+'\n];');
fs.writeFileSync(dataJsPath,dataJs,'utf8');

console.log(`JSON generados: ${gen}`);
console.log('data.js actualizado');
